### ISSUE TITLE
Prefer lesser variant when lesser is LGPL and LICENSE is GPL

### ISSUE THREAD

**Issue by benbalter** [benbalter/licensee#108]

**Comment by mlinksva** [comment]
https://www.gnu.org/licenses/gpl-howto.html

> You should also include a copy of the license itself somewhere in the distribution of your program. All programs, whether they are released under the GPL or LGPL, should include the text version of the GPL. In GNU programs the license is usually in a file called COPYING.
>
> If you are releasing your program under the LGPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER. Please note that, since the LGPL is a set of additional permissions on top of the GPL, it's important to include both licenses so users have all the materials they need to understand their rights.

If license_file gpl (2 or 3) and license_file.lesser lgpl (matching 2.0->2.1 or 3.0->3.0) then licensee should say it detected lgpl (whichever version it found) -- it can be pretty sure that that maintainer is just following convention recommended above.

**Comment by lecoursen** [comment]
It seems unlikely, but the user who reported this is asking:

> Is there anything we can do in the meantime to overwrite it? Perhaps using a .gitattributes file?

I figured it couldn't hurt to ask! 😊
