### ISSUE TITLE
Score COPYING over COPYING.foo files

### ISSUE THREAD

**Issue by benbalter** [benbalter/licensee#109]
Would need to update the scoring in https://github.com/benbalter/licensee/blob/master/lib/licensee/project_files/license_file.rb#L18.

**Comment by waldyrious** [comment]
What's the rationale for this? I would say explicit format annotation is better than implicit.

**Comment by benbalter** [comment]
if I have a `COPYING` file, one would assume that to be general to the project, while if I had a `COPYING.image` file, that would be specific to the images within the project. We want to detect the general one (and generally don't want to encourage an anti-pattern of `COPYING.frog` and so on).

**Comment by waldyrious** [comment]
Ok. I was thinking about COPYING.md or COPYING.txt. Can we exclude these patterns from this heuristic? In fact, I'd suggest ranking them higher than plain COPYING, but I'm not sure if that's consensual.

**Comment by benbalter** [comment]
For `LICENSE` [we currently score `LICENSE` over `LICENSE.md`](https://github.com/benbalter/licensee/blob/master/lib/licensee/project_files/license_file.rb#L16-L17).

**Comment by waldyrious** [comment]
Thanks. I'm assuming that that choice wasn't documented or publicly discussed, so it would be nice to either have that discussion now, or document the rationale for it. Also, I'd say it would be good to use the same extension rules (no extension, text file extension, or something else) for all the filename patterns.

**Comment by benbalter** [comment]
>  I'm assuming that that choice wasn't documented or publicly discussed, 

See https://github.com/benbalter/licensee/pull/36, https://github.com/benbalter/licensee/issues/43, https://github.com/benbalter/licensee/pull/60, and https://github.com/benbalter/licensee/pull/35#discussion_r35032032.

If you have any suggested changes to the current behavior, including the change that motivated this issue, please feel free to open a pull request. More than glad to continue discussing. :smile:

**Comment by waldyrious** [comment]
Very informative links, I'm glad they got collected in one place :)

After reading those, it seems the discussion about extensions was always about extensions as a semantic annotation (what kind of content the license applies to) rather than a syntactic annotation (what type of file the license is written into).

I offered above that the latter type should have precedence over plain filenames (for all variations thereof), and agree that the former type should indeed have lower precedence than extension-less filenames, as this issue proposes.

If there are no objections to these two heuristics, I'll gladly open a PR to tackle both.

**Comment by benbalter** [comment]
> If there are no objections to these two heuristics, I'll gladly open a PR to tackle both.

No objection here, but do you mind dropping an example here of the two types of extensions? I'm having trouble following.

**Comment by waldyrious** [comment]
Sure.

- Type 1 extension (semantic annotation): COPYING.image, LICENSE.go, etc.
- Type 2 extension (syntactic annotation): UNLICENSE.txt, COPYRIGHT.md, etc.

I also updated the wording of the second paragraph in my previous comment, hopefully making it clearer.

**Comment by benbalter** [comment]
So it sounds like you're suggesting:

* LICENSE
* LICENSE.md
* LICENSE.image

is that right? If so, 👍

**Comment by waldyrious** [comment]
exactly right :) I'll start a PR ASAP then.
