### ISSUE TITLE
Mozilla Public License not recognized anymore

### ISSUE THREAD

**Issue by pchaigno** [benbalter/licensee#115]
With the last version (`v8.4`), the license of [alnkpa/sublimeprolog](https://github.com/alnkpa/sublimeprolog) isn't recognized anymore:
```
$ licensee
License file: LICENSE
License: no license
```

It works fine with `v8.3.1`:
```
$ licensee
License file: LICENSE
License: Mozilla Public License 2.0
Confidence: 100.00%
Method: Licensee::Matchers::Exact
```

If I remember correctly, I copied the license text (in `LICENSE`) directly from http://choosealicense.com.

**Comment by benbalter** [comment]
Take a look at https://gist.github.com/benbalter/6c92eca98b28ac51b496b30cf0b60b60/revisions?w=1. Although not ideal, there are some significant formatting changes between the two, and Licensee isn't (yet) smart enough to tell the difference between a formatting change and a legally significant textual change.

**Comment by pchaigno** [comment]
Oh, I though you removed spaces, newlines, and such.
Is there any solution other than using the license hash to "fix" this?

**Comment by benbalter** [comment]
> I though you removed spaces, newlines, and such.

It does remove whitespace, but there are non-whitespace changes. We could theoretically also strip non-word characters such as the `|`s and `=`s which is what's causing the discrepancy here (and are almost never legally significant).

What's strange is that in 8.3.1, it was an exact match, and here it's not matching. Let me dig a bit deeper...

**Comment by benbalter** [comment]
With something like `content_normalized.gsub!(/[=-]{4,}/, "")` (normalizing the HRs) it's now an exact match. I'll get a PR together to fix and test.

```
script/git-repo https://github.com/alnkpa/sublimeprolog
License file: LICENSE
License: Mozilla Public License 2.0
Confidence: 100.00%
Method: Licensee::Matchers::Dice
```

**Comment by pchaigno** [comment]
Thanks @benbalter!
