### ISSUE TITLE
Support for Boost license

### ISSUE THREAD

**Issue by KindDragon** [benbalter/licensee#119]
https://github.com/boostorg/compute/blob/master/LICENSE_1_0.txt
https://github.com/boostorg/hana/blob/master/LICENSE.md

**Comment by benbalter** [comment]
Hi @KindDragon! This project doesn't curate the license information, but simply vendors the licenses and metadata provided by choosealicense.com. Please [follow these instructions](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license) to submit a pull request to get the license added upstream, and it will be automatically vendored (and detected) here.

**Comment by KindDragon** [comment]
Sorry, thank you

**Comment by KindDragon** [comment]
Hmm, they have Boost license http://choosealicense.com/appendix/

**Comment by mlinksva** [comment]
It was only added last week https://github.com/github/choosealicense.com/pull/452 and is not yet vendored by licensee.

**Comment by KindDragon** [comment]
Greate! Thank you

**Comment by benbalter** [comment]
Re-vendored the licenses via `8050466`
