### ISSUE TITLE
Support for Open Government License

### ISSUE THREAD

**Issue by lewispb** [benbalter/licensee#120]
Many open source repo's created by UK Government departments and agencies are open sourced under the Open Government Licence:

http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/

Is this something that I can include in a pull request here or should I try choosealicense.com instead?

**Comment by benbalter** [comment]
Hi @lewispb! This project doesn't curate the license information, but simply vendors the licenses and metadata provided by choosealicense.com. Please [follow these instructions](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license) to submit a pull request to get the license added upstream, and it will be automatically vendored (and detected) here.
