### ISSUE TITLE
Scan more files for licenses (including COPYING)

### ISSUE THREAD

**Issue by Wuzzy2** [benbalter/licensee#121]
Based on research at https://github.com/benbalter/licensee/issues/88, I think the method of only looking into the `LICENSE` file is pretty poor as many projects which actually have a license will be overlooked.
Of course, there will probably never a perfect algorithm, but some obvious improvements could be made:

* Scan for the existance of `COPYING`. This file seems is also very commonly used and, to my knowledge, is generally considered to be a valid synonym for `LICENSE`
* Also check for common file name suffix variants: `LICENSE.txt`, `LICENSE.md`, `COPYING.txt`, `COPYING.md`
* Ignore case (just to be safe)

Furthermore, some research should be done on other common ways software specified (e.g. are there other common file names or de facto standard practices which are easily detectible?).

Background info:
The fact that the `COPYING` file is ignored probably means that statistics based on this tool (like this one: https://github.com/blog/1964-open-source-license-usage-on-github-com) are probably WAY too pessimistic since many projects with the `COPYING` files are simply overlooked.
At least, any such statistics should be more carefully worded by claiming that *at least* X% of the projects have a license, rather than claiming an exact number. I predict that the number of detected licensed projects will “surprisingly” skyrocket by the simple change to also detect `COPYING`. :D

**Comment by benbalter** [comment]
Hi @Wuzzy2! Thanks for opening this issue. We already look at lots more than just vanilla `LICENSE`. See https://github.com/benbalter/licensee/blob/3692df44ab32772a98a3aec8a44080f7dbe3d50a/lib/licensee/project_files/license_file.rb#L15-L25 for the details. I *believe* all the examples you cited are currently handled, but please let me know if that's not currently the case.

**Comment by waldyrious** [comment]
I'd also point out [test_license_file.rb#L32-L55](https://github.com/benbalter/licensee/blob/3692df44ab32772a98a3aec8a44080f7dbe3d50a/test/licensee/project_files/test_license_file.rb#L32-L55), which shows various examples of license filename patterns that licensee currently recognizes.

**Comment by Wuzzy2** [comment]
Then the readme file is clearly out of date.

**Comment by waldyrious** [comment]
Good point. This is now tracked as #122.

**Comment by benbalter** [comment]
> Then the readme file is clearly out of date, as it only mentions LICENSE.

[It's there](https://github.com/benbalter/licensee#what-it-looks-at), but I'm working on updating the documentation to make that more clear via #122 as @waldyrious pointed out.
