### ISSUE TITLE
Add ISC

### ISSUE THREAD

**Issue by jab** [benbalter/licensee#127]
Just came across this via https://github.com/blog/2252-license-now-displayed-on-repository-overview, cool.

The ISC license fulfills requirements 1. and 2. under https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license.

As for requirement 3, https://github.com/search?q=ISC+filename%3ALICENSE&type=Code currently produces 9,238 results. Would you relax the requirement of 10,000 in this case, since it's so close?

(I actually chose ISC based on the recommendation of http://choosealicense.com when that site first came out, but it looks like it changed since then and would now recommend MIT based on what I was looking for?)

/CC @waldyrious, who thinks ISC is the neatest of the short, permissive licenses (MIT, BSD, etc.)

**Comment by benbalter** [comment]
The ISC license [is included](https://github.com/benbalter/licensee/blob/master/vendor/choosealicense.com/_licenses/isc.txt). Do you have an example of it not being detected?

**Comment by jab** [comment]
Oh good and sorry I missed that, but I'm not seeing it being detected for my https://github.com/jab/bidict project nor for the first few projects I click through in the results for https://github.com/search?q=ISC+filename%3ALICENSE&type=Code -- could it be a bug in ISC detection?

**Comment by benbalter** [comment]
>  I'm not seeing it being detected for my https://github.com/jab/bidict project

I told GitHub to redetect the license, and it is properly detected now. We've been using various versions of Licensee on GitHub, and a prior version may not have properly detected it.

> the first few projects I click through in the results for https://github.com/search?q=ISC+filename%3ALICENSE&type=Code 

We do not currently consider a license a match if the LICENSE file contains a reference to the license's abbreviation.

**Comment by jab** [comment]
Thanks, that fixed it!

**Comment by waldyrious** [comment]
@jab thanks for the heads-up!

> We do not currently consider a license a match if the LICENSE file contains a reference to the license's abbreviation.

@benbalter can you clarify this? Do you mean "if the license file contains *only* a reference to the abbreviation", or "if it contains the abbreviation at all"? I'm concerned since I've been sending out PRs adding the license title to the LICENSE file of various files, to make the license more readily identifiable for humans.

**Comment by jab** [comment]
@waldyrious I think that's referring to LICENSE files like [this](https://github.com/itsomx/webpage/blob/master/LICENSE) and [this](https://github.com/Ubiquitine/gentoopi/blob/master/root-fs/var/db/pkg/app-misc/tmux-1.7/LICENSE) (from the top results for https://github.com/search?q=ISC+filename%3ALICENSE&type=Code) which say nothing but "ISC".

@benbalter Btw, do you know if choosealicense.com did switch from recommending ISC to MIT at some point and if so what the reasoning was?

**Comment by benbalter** [comment]
> do you know if choosealicense.com did switch from recommending ISC to MIT at some point and if so what the reasoning was?

It has never changed *from* MIT. MIT was one of the original three. See https://github.com/github/choosealicense.com/search?q=MIT+ISC&state=closed&type=Issues&utf8=%E2%9C%93 for prior discussions, although I can't find anything specific about moving from MIT to ISC, although I remember that discussion happening and being ultimately declined.

**Comment by waldyrious** [comment]
IIRC, what happened was a trim-down of the licenses displayed in the "more options are available" (/licenses) page. This is explained in detail in https://github.com/github/choosealicense.com/pull/386.
