### ISSUE TITLE
`licensee directory` fails, but `licensee file` succeeds

### ISSUE THREAD

**Issue by evhub** [benbalter/licensee#132]
This behaviour occurred when working with the repository https://github.com/evhub/coconut.

When running `licensee ./coconut`, the correct file, `LICENSE.txt`, is identified, but licensee fails to detect the license. If I instead directly run `licensee ./coconut/LICENSE.txt`, however, licensee correctly detects that the file is a 96% match for Apache 2.0.

I don't understand how this could be anything other than a bug, since licensee is detecting the correct license file, and knows what type of license that license file is, but still can't detect the license. Some help understanding what's going on and potential workarounds would be appreciated.

Here's the full log from my terminal session:

```
$ licensee ./coconut
License file: LICENSE.txt
Attribution: Copyright 2015-2016 Evan Hubinger
License: Not detected

Here's the closest licenses:
$ licensee ./coconut/LICENSE.txt
License file: LICENSE.txt
Attribution: Copyright 2015-2016 Evan Hubinger
License: Apache License 2.0
Confidence: 96.58%
Method: Licensee::Matchers::Dice
```

**Comment by benbalter** [comment]
I can't speak to the inconsistent behavior (and can't recreate it), but the the license not being recognized is the expected behavior, as it has the apache boilerplate prepended. See https://github.com/benbalter/licensee/issues/103.

**Comment by evhub** [comment]
@benbalter Modified the license file not to have the boilerplate prepended (<https://github.com/evhub/coconut/blob/develop/LICENSE.txt>), and I still get the same behaviour.

**Comment by benbalter** [comment]
@evhub compare that license text with http://choosealicense.com/licenses/apache-2.0/. The licenses has a copyright header added to the top and the license boilerplate removed from the end and is properly being detected as not matching the Apache license.

**Comment by evhub** [comment]
@benbalter For other repositories with similar Apache 2.0 licenses (with no boilerplate at the bottom), however, licensee seems to work correctly. For example, [this repository](https://github.com/Yelp/undebt) also has a version of the Apache 2.0 license without the boilerplate at the bottom and with a copyright header at the top, and yet is detected as Apache 2.0. Thus, it seems to me like something more is going on than just that the license file doesn't include the boilerplate (which isn't part of the legal license, and so theoretically shouldn't be necessary).
