### ISSUE TITLE
Expose license hash for unrecognized licenses

### ISSUE THREAD

**Issue by pchaigno** [benbalter/licensee#133]
Currently, the license hash (#76) is only exposed if the license is recognized.
The initial purpose of the license hash (#67) was to be able to identify uniquely non-standard licenses. Unless I've missed something (?), this isn't currently possible.

I'm not sure how to expose it. The appropriate place would be `License` but there does not seem to be a `License` object created if no license is actually recognized...

**Comment by benbalter** [comment]
The following should work:

```ruby
project = Licensee.project("path/to/project")
project.license_file.hash
> "750260c322080bab4c19fd55eb78bc73e1ae8f11"
```

**Comment by pchaigno** [comment]
Oo, right. So I did miss something!
Thanks @benbalter! :smiley:
