### ISSUE TITLE
Synonyms in disclaimer 

### ISSUE THREAD

**Issue by waldyrious** [benbalter/licensee#139]
I recently changed "AUTHOR" to "COPYRIGHT HOLDERS" in the disclaimer of the ISC license in one of my projects, but now Licensee doesn't recognize the license, per the shields.io badge which IIUC gets the license data from the GitHub API: https://github.com/waldyrious/primerpedia#primerpedia

I have a few questions about this (note: I'm not seeking legal advice, just informed opinions):

1. Is the resulting text still the ISC license, considering that the semantics are the same, even though the text doesn't match the original template verbatim?
2. Is the new wording indeed more precise (which was my intention)?
3. Does this change drop the match % below the threshold only because this license's text is short (i.e. the same change would not affect Licensee's assessment of a larger license)? And if so, should it?
4. Could Licensee perhaps use a set of equivalent terms (author / copyright holder, plural variations thereof, etc.) and not count these variations toward lowering the matching score?

**Comment by mlinksva** [comment]
I have no answers (other than to 2, I'd say different rather than more precise) but apart from a desire to get licensee recognizing particular variations right now, you probably know and others should that there's an effort to define a format that will enable precisely specifying what variations of licenses should be considered the same http://wiki.spdx.org/view/Legal_Team/Templatizing

**Comment by waldyrious** [comment]
I actually didn't know about that effort, thanks for the link! I'll keep an eye on that project.

As for "different rather than more precise", the rationale was that copyright can be transferred, while authorship is absolute. In the context of a license, IIUC the former is that matters in terms of who can grant permissions on the work (even though the two tend to coincide most of the time).

**Comment by mlinksva** [comment]
The disclaimer isn't a permission. This may not be widely known, accepted, or effective, but disclaimers of warranty/limitations of liability in some open source licenses aren't AFAICT meant to only protect licensors (copyright holders). This avoids open source software having to come with disclaimers separate from the license.

**Comment by waldyrious** [comment]
> The disclaimer isn't a permission.

I didn't mean to imply that, apologies if that's what it came off as.

> disclaimers of warranty/limitations of liability in some open source licenses aren't AFAICT meant to only protect licensors (copyright holders).

Precisely. It's the licensors (copyright holders) that require this protection, since they're the ones licensing the work, not (necessarily) the author(s).

**Comment by mlinksva** [comment]
My point was precisely the opposite. Parties other than the copyright holders could conceivably offer warranties and/or be held liable. Check out for example MPL-2.0 and GPL-3.0 which mention some of them explicitly.

**Comment by waldyrious** [comment]
My bad, I did misread your comment. But won't "author" then leave out the copyright holders (if they're different people), for the same reason?

**Comment by mlinksva** [comment]
Thus my "different" parenthetical in my first comment above. :smile: Also again, I've no idea whether this is important, effective, etc, or not. Would be interesting to know from the ISC drafters why they drafted the disclaimer the way they did.

Back to the potentially actionable bits for licensee: I doubt ensuring it detects new variations in short licenses is in its sweet spot, unless/until such variations are widely used. Just my off the cuff opinion, as is all of the above.

**Comment by waldyrious** [comment]
Thanks for the patient explanations; I think we're in the same page now (I'll change my licenses back to "author", since "copyright holder" doesn't appear to be necessarily better).

Hopefully someone can chime in with actual numbers of occurrences of these variations, although I doubt it is indeed warranted. I suppose supporting such variations could make the matching test significantly slower... if that is confirmed, I suppose this issue can be closed.

**Comment by waldyrious** [comment]
By the way, it appears even minute changes make the recognition fail. [Here's the diff](https://www.diffchecker.com/fUA6p1a7) between the [text of the ISC license](http://choosealicense.com/licenses/isc/) at choosealicense.com, and the [text of the license in my repo](https://github.com/waldyrious/wikispeed/blob/gh-pages/LICENSE.md).

Running Licensee locally gives me the following output:

```
2016-10-03 16:10:09] ~/repos/wikispeed$ licensee
License file: LICENSE.md
License hash: 4ee643c1a3133ce2c8cb89de930e03335d8721df
Attribution: Copyright (c) 2016, Waldir Pimenta and [contributors]

Here's the closest licenses:
* Zlib similarity: 40.51%
```

Is this expected? Looks like a bug to me.

**Comment by benbalter** [comment]
@waldyrious in short, this is the expected (and desired) behavior. If you look at [the problems the project is trying to solve](https://github.com/benbalter/licensee#the-problem):

> You've got a project with a license file, but which license is it? **Has it been modified?**

An open source license is a legal contract, and when it comes to legal contracts, words matter. Changing "author" to "copyright holder" could have significant implications on the rights of downstream users (or upstream contributors), and thus Licensee properly fails to detect the license as the original, unmodified license. Because computers can't give legal advice, in that case, the best course of action for a downstream user would be to consult a lawyer on the legal implications of using software with a non-standard, potentially non-open-source license.

**Comment by waldyrious** [comment]
Understood. I'm curious though about the mismatch in identifying the license as closer to the Zlib license than the ISC license. Would't that be something to investigate?

**Comment by benbalter** [comment]
> closer to the Zlib license than the ISC license.

At 40%, I'm not too concerned (since it needs 95% confidence to call it the license). It's likely a result of looking at the wordset (unique words), rather than the raw text.

**Comment by waldyrious** [comment]
Ok then. I was wondering it it could be symptomatic of something wrong with the matcher which could cause problems elsewhere. Anyway, considering that minor differences in the license text are deliberately not supported by Licensee (maybe later if the SPDX's templatizing work bears fruits in that regard), I'll close this issue. Thanks both for the informative replies.

**Comment by waldyrious** [comment]
@benbalter any idea why the recognition hasn't been updated for my two repos ([wikispeed ](https://github.com/waldyrious/wikispeed) and [primerpedia](https://github.com/waldyrious/primerpedia)) where I had experimented with this wording change? I understand that there may be a delay, but the change from recognized to unrecognized was pretty quick, while the opposite seems to not have been taken up even after more than a week.
