### ISSUE TITLE
LGPL detection inconsistency

### ISSUE THREAD

**Issue by Bilge** [benbalter/licensee#143]
If LGPLv3 is copied verbatim to files named `COPYING` and `COPYING.LESSER`, it is detected correctly as _LGPL-3.0_. If the same files are renamed to `LICENSE` and `LICENSE.LESSER`, it is detected incorrectly as _GPL-3.0_.

Furthermore, if both parts of the license are copied to a single file it is not detected at all. Perhaps this is intended behaviour but I can't see why.

**Comment by benbalter** [comment]
> Furthermore, if both parts of the license are copied to a single file it is not detected at all. Perhaps this is intended behaviour but I can't see why.

Correct. This is the intended behavior, and was implemented via https://github.com/benbalter/licensee/issues/113. See https://github.com/benbalter/licensee/issues/108#issuecomment-246000853 for context. Licensee supports detection when the full license text, and only the license text is in a `LICENSE` or similar file, or when maintainers follow the license's implementation instructions (as in this case, is `COPYING.LESSER` not `LICENSE.LESSER`)

**Comment by Bilge** [comment]
That's not what I was referring to when talking about *intended behaviour*; I was shoe-horning a sideline issue into this same issue which was probably a bad idea.

To the point at hand, #108 claims the following:

>If the LICENSE is a GPL variant, check for a LICENSE.lesser file

However, this bug report is intended to clearly state that this is not happening.

**Comment by benbalter** [comment]
> If the LICENSE is a GPL variant, check for a LICENSE.lesser file

Gotcha. Thanks for clarifying. That was a typo in #113, now corrected with a note to that affect.

**Comment by heuermh** [comment]
> If LGPLv3 is copied verbatim to files named COPYING and COPYING.LESSER, it is detected correctly as LGPL-3.0.

Is that true?  I see inconsistencies, in that this repo is correctly labeled LGPL 3.0

https://github.com/heuermh/adam-dishevelled-bio

and these are incorrectly labeled GPL 3.0

https://github.com/heuermh/adam-snpeff
https://github.com/heuermh/dishevelled-bio
https://github.com/heuermh/ensembl-rest-client
https://github.com/heuermh/genotype-list
https://github.com/heuermh/ngs
https://github.com/heuermh/service-feature

It should be the same `COPYING` AND `COPYING.LESSER` file in all cases.

**Comment by Bilge** [comment]
@benbalter This detection mechanism doesn't make sense. Why can GPL be detected in files named LICENSE *or* COPYING but LGPL can only be detected in a file named COPYING.LESSER? If you support different prefixes, e.g. *LICENSE* then they should all be compatible with the *.LESSER* suffix.

**Comment by benbalter** [comment]
> and these are incorrectly labeled GPL 3.0

That was due to the repositories being detected with a prior version of licensee. I redetected their licenses, and they now properly display LGPL.

> Why can GPL be detected in files named LICENSE or COPYING but LGPL can only be detected in a file named COPYING.LESSER?

That's not exactly accurate. LGPL will be detected if:

1. Any license file contains the text of the LGPL license, OR
2. The detected license file is GPL AND theres a `COPYING.lesser` file, which contains the LGPL (per the license's own implementation instructions)

**Comment by heuermh** [comment]
@benbalter Thanks for the license bump on those repositories!

**Comment by iljah** [comment]
I have the same issue at https://github.com/fmihpc/dccrg where I have COPYING and COPYING.LESSER as recommended by FSF. Note that FSF recommends .LESSER not .lesser (https://www.gnu.org/licenses/gpl-howto.en.html), could this be fixed if that's the problem? Thanks!

**Comment by benbalter** [comment]
> Note that FSF recommends .LESSER not .lesser (https://www.gnu.org/licenses/gpl-howto.en.html), could this be fixed if that's the problem?

The filename comparison is [case insensitive](https://github.com/benbalter/licensee/blob/6dffa7383264aa64742fc31eb170c1a38f465029/lib/licensee/project_files/license_file.rb#L45-L48)

> I have the same issue at https://github.com/fmihpc/dccrg

It must have been detected using an older version of Licensee before this was implemented. I redetected the license, and it's now properly identified as LGPL.
