### ISSUE TITLE
MIT license sometimes recognized, sometimes not

### ISSUE THREAD

**Issue by sschuberth** [benbalter/licensee#147]
First of all I'm sorry if this is the wrong place to report this, but as I now this gem [is powering GitHub's license information](https://developer.github.com/v3/licenses/), I thought the most knowledgeable people will read this here.

 These [data-lens](https://github.com/heremaps/data-lens-javascript-examples) and [jsfiddle](https://github.com/heremaps/jsfiddle-github) project have the same LICENSE file, which is MIT. Yet the GitHub web UI only displays the license information for the latter. Any idea why that is?

Running licensee locally on these LICENSE file yields

    $ bin/licensee ~/Downloads/LICENSE-jsfiddle.txt
    License file: LICENSE-jsfiddle.txt
    License hash: 84885902123f8c5e8ad5e6cbc02fe2a34e59d1ef
    Attribution: Copyright (c) 2016 HERE Europe B.V.

    Here's the closest licenses:
    * Unlicense similarity: 58.49%

Given this, I would assume that also for the jsfiddle project the license should not be recognized. I can fix the recognition by removing the first (long) line from the LICENSE file, which is custom text that does not actually belong to the license. Yet my question is why in the web UI for jsfiddle the license info displays correctly.

**Comment by benbalter** [comment]
@sschuberth this is the expected behavior. The inconsistency is due to the fact that jsfiddle's license was detected with a prior, less strict version. I queued a redetection job, and it is not properly NOT detecting the MIT license for both. 

The issue is this line:

> Unless otherwise noted in a LICENSE file for specific files or directories, the files in this repository are under the following license.

While Humans understand what that line says, unfortunately, robots do not. That line could say "This project isn't licensed, but here's a copy of the MIT license, because I think it looks cool:". As such, Licensee doesn't know if the line is legally significant, and properly says it's not the MIT license.

**Comment by sschuberth** [comment]
> The inconsistency is due to the fact that jsfiddle's license was detected with a prior, less strict version. I queued a redetection job, and it is not properly NOT detecting the MIT license for both.

I was assuming something like that. Then my obvious next question is: What makes GitHub re-run the detection job? Changes to the repository? Changes to licensee? If so, when? Once a day?

**Comment by waldyrious** [comment]
> What makes GitHub re-run the detection job?

I'd like to know this too (see https://github.com/benbalter/licensee/issues/139#issuecomment-252737035)

**Comment by benbalter** [comment]
> What makes GitHub re-run the detection job?

It should run near-instantly following a push that touches any matching LICENSE file (but is then cached until the next subsequent push, where it is re-run with the latest version of Licensee).

**Comment by sschuberth** [comment]
Thanks for the details. One more question, even if I'm going slightly off-topic: Does GitHub support the case where there are different LICENSE files per (orphan) branch? I.e. if I switch branches in the web UI, is the detected license information supposed to update accordingly?

**Comment by benbalter** [comment]
> if I switch branches in the web UI, is the detected license information supposed to update accordingly?

That's not currently supported. There is a one-one relationship between repositories and licenses.

**Comment by sschuberth** [comment]
> It should run near-instantly following a push that touches any matching LICENSE file

Sorry, yet one more thing: So does that mean no re-run is queued if only licensee is updated? Is that the reason why the jsfiddle license was not updated, as the LICENSE file was not changed, but only licensee was made more strict?

**Comment by benbalter** [comment]
> So does that mean no re-run is queued if only licensee is updated? Is that the reason why the jsfiddle license was not updated, as the LICENSE file was not changed, but only licensee was made more strict?

Correct. With nearly 40M projects, it's not feasible to redetect every project's license every time Licensee is updated. If you notice a project that you think may need a bump, feel free to email support and we can redetect the license.
