### ISSUE TITLE
0BSD sometimes detected incorrectly as ISC

### ISSUE THREAD

**Issue by rqou** [benbalter/licensee#149]
One of my [repositories](https://github.com/rqou/miscellany) uses a [0BSD](https://opensource.org/licenses/FPL-1.0.0) license, but GitHub/Licensee mis-detects it as ISC. I thought that this problem was caused by [choosealicense not having the 0BSD license](https://github.com/github/choosealicense.com/issues/464), and the developers there told me to also file an issue here.

**Comment by mlinksva** [comment]
I believe the license for that repo was detected with an older version of licensee that was less strict (the LICENSE file was modified 3 months ago).

Based on an earlier comment https://github.com/benbalter/licensee/issues/147#issuecomment-256145253 ...

>> So does that mean no re-run is queued if only licensee is updated? Is that the reason why the jsfiddle license was not updated, as the LICENSE file was not changed, but only licensee was made more strict?
>
> Correct. With nearly 40M projects, it's not feasible to redetect every project's license every time Licensee is updated. If you notice a project that you think may need a bump, feel free to email support and we can redetect the license.

... you can probably [contact support](https://github.com/contact).

**Comment by benbalter** [comment]
> I believe the license for that repo was detected with an older version of licensee that was less strict (the LICENSE file was modified 3 months ago).

I believe that's correct. It is now properly *not* being detected as ISC.

**Comment by rqou** [comment]
Just to clarify, are you saying that with the latest version licensee will detect 0BSD as nothing, but adding 0BSD to the upstream choosealicense project will then enable licensee to detect 0BSD as 0BSD?

**Comment by benbalter** [comment]
> Just to clarify, are you saying that with the latest version licensee will detect 0BSD as nothing, but adding 0BSD to the upstream choosealicense project will then enable licensee to detect 0BSD as 0BSD?

Correct.

**Comment by benbalter** [comment]
Well, to clarify, the latest version will properly detect 0BSD as an unknown license, rather than resulting in a false positive of ISC.

**Comment by rqou** [comment]
In this case, I believe there is no issue here. I will close this for now.
