### ISSUE TITLE
Detect MIT-LICENSE file

### ISSUE THREAD

**Issue by bkeepers** [benbalter/licensee#15]
I don't know where the convention comes from, but I've seen enough repos with a `MIT-LICENSE` file that I'm guessing it was a recommended approach at some point. For example: https://github.com/github/brakeman.

Would it make sense to add support for this?

**Comment by benbalter** [comment]
Wow. Yeah. Looks like [2+ million repos](https://github.com/search?p=1&q=Permission+is+hereby+granted++filename%3AMIT-LICENSE&ref=searchresults&type=Code&utf8=%E2%9C%93)

Are you able to submit a pull request to https://github.com/benbalter/licensee/blob/master/lib/licensee/project.rb#L5-L13?
