### ISSUE TITLE
Ability to detect copyright notice without explicit year

### ISSUE THREAD

**Issue by benbalter** [benbalter/licensee#156]
How do we distinguish [this line](https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/apache-2.0.txt#L137) from [this line](https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/zlib.txt#L28).

The Zlib license uses a line starting with `(c)` (followed by a date and an arbitrary string) to represent the copyright line.

The Apache license uses a line starting with `(c)` followed by arbitrary text to represent the third bullet of a numbered list.

We had been using the date to distinguish the two. If we treat the 2nd as copyright, I think we're going to get a lot of false positives (Licensee thinks it has a copyright), or false negatives (with that line stripped, license comparison fails).

I think our best bet would be to strip the title (in multiple variants) if it's the start of the license, and the only thing on the line (other than whitespace) and to then assume if the new first line starts with a copyright identifier, that whole line is the copyright.

**Comment by willbar** [comment]
For the Microsoft open source projects it is standard practice not to include the year in the copyright message, as a result this issue causes the license not to be detected for a large number of our repositories.

Is there anything I can do to help complete/validate this PR?

**Comment by benbalter** [comment]
@willbar once tests are passing for https://github.com/benbalter/licensee/pull/163 and it's merged, that should resolve this issue.
