### ISSUE TITLE
COPYING.LESSER (i.e. all caps) not detected and repo wrongfully classified as GPL

### ISSUE THREAD

**Issue by aothms** [benbalter/licensee#158]
I have read issue https://github.com/benbalter/licensee/issues/108 and pr https://github.com/benbalter/licensee/pull/113 in which lgpl detection is special cased. #108 also quotes the instructions from the license saying

> If you are releasing your program under the LGPL, you should also include the text version of the LGPL, usually in a file called COPYING.LESSER ...

In the code I read two variations, but not the all caps recommendation above.

~~~
        'COPYING.lesser' => 1,
        'copying.lesser' => 1,
~~~

In my naivety I assume this is the reason my repository here on github is wrongfully classified as GPL, where it should be LGPL, as I have a file named `COPYING.LESSER`. Am I correct in my understanding or is this somehow intentional?

**Comment by benbalter** [comment]
@aothms I added an explicit test via https://github.com/benbalter/licensee/pull/159, and it looks like it's passing (meaning that it's accounted for).

Those are tests, but the relevant line is https://github.com/benbalter/licensee/blob/6dffa7383264aa64742fc31eb170c1a38f465029/lib/licensee/project_files/license_file.rb#L47, which is case insensitive (or at least should be).

**Comment by aothms** [comment]
Many thanks for your quick response, I'm really rather illiterate in ruby. Just hope my repo (https://github.com/IfcOpenShell/IfcOpenShell) can show op as LGPL here on github, that single letter can make a difference to some people.

I've been trying to test things locally, but so far not succeeding. If I especially point licensee to the COPYING file (using a fresh download from gnu officially) I can get it to detect *GPL* [1], but using the entire directory (which I assume is necessary to have *LGPL* appended) I get a different hash for the same `COPYING` file and no match. This seems to be similar to https://github.com/benbalter/licensee/issues/132 somehow.

~~~
wget -qOCOPYING https://www.gnu.org/licenses/gpl-3.0.txt
wget -qOCOPYING.LESSER https://www.gnu.org/licenses/lgpl-3.0.txt
~~~
~~~
$ ~/licensee/bin/licensee COPYING
License file: COPYING
License hash: 7d8eb971d140e485a1cdf7dbabfbb718db2e3dfa
Attribution: Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
License: GNU General Public License v3.0
Confidence: 99.90%
Method: Licensee::Matchers::Dice
~~~
~~~
$ ~/licensee/bin/licensee .
License file: COPYING
License hash: 8e7c567fed531449221e8e03e9119f38fdd7d4e7
Attribution: Copyright (C) 2007 Free Software Foundation, Inc. <http://fsf.org/>
~~~

[1] The fixture in this repository has some white space differences so it's not an exact match https://raw.githubusercontent.com/benbalter/licensee/master/spec/fixtures/lgpl/LICENSE

**Comment by Tyrrrz** [comment]
I have the same issue, but in my case both of the licenses are in the same file (goes like copyright -> GPLv3 -> LGPLv3), which github detects as GPLv3

**Comment by devemux86** [comment]
Same problem with our [Mapsforge](https://github.com/mapsforge/mapsforge) repository.

And until recently problem existed also in our [VTM](https://github.com/mapsforge/vtm) repository, but now it's correctly detected as LGPL.

**Comment by benbalter** [comment]
> Same problem with our Mapsforge repository.

GitHub caches the detected license. I redetected the Mapsforge license, but if you have any other repos, GitHub support can redetect the license (or you can update the LICENSE file). 

If anyone can reproduce the problem locally, I'd love to be able to recreate it.

**Comment by devemux86** [comment]
Thanks for the quick solution!

> or you can update the LICENSE file

This would trigger a license re-detection?
And how update without pushing a different file?
(we have original COPYING and COPYING.LESSER)

**Comment by benbalter** [comment]
> This would trigger a license re-detection?

Any push that modifies a license file queues a redetection job. You could do this, e.g., by changing whitespace or updating the copyright year.
