### ISSUE TITLE
Bug: Licensee can't handle multi-line copyright statements

### ISSUE THREAD

**Issue by david-a-wheeler** [benbalter/licensee#162]
Licensee fails to determine that our BadgeApp has a bog-standard MIT license.

The reason is that the CII BadgeApp has a 2-line copyright statement (it won't fit on 1 80-column line):
> Copyright (c) 2015-2016 The Linux Foundation,
> the Institute for Defense Analyses, and other project contributors.

The rest of the text is a bog-standard MIT license, but licensee fails to determine its license.  The problem appears to be that licensee strips lines matching a copyright statement, but not the following line if it continues the copyright text.

Sample file which causes the failure is here:
https://github.com/linuxfoundation/cii-best-practices-badge/blob/c23e6c6c88956192266bbf243ba630a6887ef9f2/LICENSE

This wouldn't matter as much if licensee accepted issue #85, which would let people directly specify the actual license in a computer-processable way.  However, since there's no way to provide computer-processable information to licensee, any error or limitation of licensee produces "don't know".  But that's a separate issue; licensee should still be able to handle two-line copyright statements.

Thanks!

**Comment by benbalter** [comment]
Definitely a valid limitation of the current approach and thanks for opening the issue.

I have been noodling with the idea of rewriting how licenses are normalized to remove the title if it's the start of the file, and to then anchor the copyright to the start of the file (which could be more lax and take into account single line breaks).

In the meantime, I think the only way to implement this would be to assume the line after the copyright line is part of the copyright line if it's separated by a single line break, which isn't always the case.

**Comment by david-a-wheeler** [comment]
The code could try it both ways, and see which way gives a more specific answer.

**Comment by waldyrious** [comment]
@benbalter any hints why the license detection isn't working for [tldr-pages/tldr](https://github.com/tldr-pages/tldr/blob/master/LICENSE.md) even after https://github.com/tldr-pages/tldr/commit/8f1b910ef6d440d7349537d8e1f62ba183a0db05 re-introduced a single-line copyright notice?

**Comment by benbalter** [comment]
> any hints why the license detection isn't working

@waldyrious what do you mean by "isn't working"? The licensee appears to be detected as MIT:

```
➜  licensee git:(master) script/git-repo https://github.com/tldr-pages/tldr/ --license mit
License: MIT License
Matched files: ["LICENSE.md", "package.json"]
LICENSE.md:
  Content hash: d64f3bb4282a97b37454b5bb96a8a264a3363dc3
  Attribution: Copyright (c) 2014 the [TLDR team](https://github.com/orgs/tldr-pages/people) and [contributors](https://github.com/tldr-pages/tldr/graphs/contributors)
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: MIT License
package.json:
  Confidence: 90.00%
  Matcher: Licensee::Matchers::NpmBower
  License: MIT License
Comparing to MIT License:
  Input length: 1020
  License length: 1020
  Similarity: 100.00%
  Exact match!
```

**Comment by waldyrious** [comment]
@benbalter it looks like GitHub's instance needs a nudge, then? There is no license metadata shown in https://github.com/tldr-pages/tldr/blob/master/LICENSE.md. I assumed (as you mentioned elsewhere) that the change tldr-pages/tldr@8f1b910 would have triggered a re-detection, but that didn't seem to happen.

**Comment by benbalter** [comment]
@waldyrious I checked, and it is now correctly detected.

**Comment by waldyrious** [comment]
Thanks, and sorry for the noise. I would actually make a new commit re-wrapping the copyright statement line to trigger a re-detection, but this very issue would then make detection fail.

In that regard (and getting back on-topic), is there any info you could share on when you plan work on this? Do let us know if there's something other people could do to help move this issue along.

**Comment by benbalter** [comment]
> In the meantime, I think the only way to implement this would be to assume the line after the copyright line is part of the copyright line if it's separated by a single line break, which isn't always the case.

@waldyrious I'm not sure that we can implement this, at least, we don't have a solid solution yet. If I have

```
Copyright 2017 Ben Balter
and some other contributors
```

That's indistinguishable from a computer to

```
Copyright 2017 Ben Balter
and if you contribute you owe me a puppy
```

**Comment by waldyrious** [comment]
Fair point. But isn't that already the case, with

    Copyright 2017 Ben Balter, and if you contribute you owe me a puppy

?
