### ISSUE TITLE
Attribution line found in non-templated CC-BY/BY-SA license texts

### ISSUE THREAD

**Issue by mlinksva** [benbalter/licensee#169]
> License file: LICENSE
> License hash: bec83478a124efb1beb8500ee952ffcc80a87b2b
> Attribution: copyright and certain other rights. Our licenses are
> License: Creative Commons Attribution 4.0
> Confidence: 100.00%
> Method: Licensee::Matchers::Dice

The regex defined at https://github.com/benbalter/licensee/blob/cbd96aed7dfd8e91ef780e029e5e6015c3486077/lib/licensee/matchers/copyright_matcher.rb#L9 and used at https://github.com/benbalter/licensee/blob/cbd96aed7dfd8e91ef780e029e5e6015c3486077/lib/licensee/project_files/license_file.rb#L43 matches some text within these licenses.

Few potential ways to fix:

1. Don't look for attribution in licenses known not to be templates (eg without `[fill-in-fields]`)
2. Only look for attribution in first part of license text (some reasonable number of lines or characters)
3. Hardcode avoidance of particular matched line above

**Comment by benbalter** [comment]
@mlinksva Can you point to an example license file? (e.g., how'd you generate the above output)? Think I know what the problem is, and should be an easy fix.

**Comment by mlinksva** [comment]
I ran on https://github.com/github/open-source-guide to get output, should've noted!

**Comment by benbalter** [comment]
Fix in https://github.com/benbalter/licensee/issues/170.
