### ISSUE TITLE
CC0 not being recognized when following creativecommons.org instructions

### ISSUE THREAD

**Issue by C4K3** [benbalter/licensee#172]
First I'm sorry if this is the wrong place, the root of this issue is that choosealicense uses a slightly edited version of CC0 compared to the one CC distributes, so this might be the wrong place.

Currently licensee cannot detect CC0 added as per the instructions at https://wiki.creativecommons.org/wiki/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F instead giving the following output
```
License file: COPYING
License hash: f5b7dd1f4796769f765ab4b8d40304c2bf1bcc47

Here's the closest licenses:
* LGPL-3.0 similarity: 29.60%
```
The reason for this appears to mostly be the disclaimer, if you remove that then it gets correctly recognized
```
License file: COPYING
License hash: f2d25c552d35d3e35b5041105b993da5a4b058c9
License: Creative Commons Zero v1.0 Universal
Confidence: 98.59%
Method: Licensee::Matchers::Dice
```

**Comment by mlinksva** [comment]
The license text used by licensee was introduced in https://github.com/github/choosealicense.com/pull/126 (licensee vendors choosealicense.com license texts) presumably by copying and pasting from https://creativecommons.org/publicdomain/zero/1.0/legalcode though I'm not sure how to explain the link at the end. Probably should be updated with https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt or https://spdx.org/licenses/CC0-1.0.html ... latter marks disclaimer as optional and doesn't have first line "Creative Commons Legal Code" (probably should be present there but also marked as optional).

I'm not sure what the right solution for licensee is at this point given it doesn't know anything about optional sections, but I made https://github.com/github/choosealicense.com/pull/488 updating the license text from https://creativecommons.org/publicdomain/zero/1.0/legalcode.txt in case that's useful for testing.

**Comment by red-001** [comment]
why bot

**Comment by anowlcalledjosh** [comment]
Any chance this could be reopened? The issue of CC0 not being recognised is still happening.
