### ISSUE TITLE
Similar licenses being reported as the same

### ISSUE THREAD

**Issue by christianbundy** [benbalter/licensee#177]
I have a repository using the [FPL](https://opensource.org/licenses/FPL-1.0.0), but it's being registered as an [ISC](https://opensource.org/licenses/ISC) license. I'm guessing that's because:

> By calculating the percent changed from the known license to the license file, you can tell, e.g., that a given license is 95% similar to the MIT license, that 5% likely representing legally insignificant changes to the license text.

The textual difference is small, but reporting the condition of "License and copyright notice" above a license without that condition is no bueno. What are the steps to resolve errors like this? Thanks!

**Comment by mlinksva** [comment]
@christianbundy can you point to the repo? Unless it is very recent, this has likely been resolved (see #149) and the license just needs to be re-detected for the repo.

**Comment by christianbundy** [comment]
Hey, thanks for the quick response. Here are some samples:

- https://github.com/fraction/fraction.github.io/blob/master/LICENSE
- https://github.com/fraction/guess-who/blob/master/LICENSE
- https://github.com/fraction/meteor-exports/blob/master/LICENSE
- https://github.com/fraction/node-hacker-news-api/blob/master/LICENSE
- https://github.com/fraction/exports-polyfill/blob/master/LICENSE
- https://github.com/fraction/whereami/blob/master/LICENSE
- https://github.com/fraction/news/blob/master/LICENSE
- https://github.com/fraction/dollar-sign/blob/master/LICENSE
- https://github.com/fraction/meteor-stellar/blob/master/LICENSE
- https://github.com/fraction/murder/blob/master/LICENSE
- https://github.com/fraction/set-timer/blob/master/LICENSE
- https://github.com/fraction/readme-boilerplate/blob/master/LICENSE
- https://github.com/fraction/sshcd/blob/master/LICENSE
- https://github.com/fraction/homebrew-formulae/blob/master/LICENSE
- https://github.com/fraction/free-public-license/blob/master/LICENSE

**Comment by mlinksva** [comment]
It looks like the current licensee code will not get a false positive:

> $ script/git-repo https://github.com/fraction/fraction.github.io
> License file: LICENSE
> License hash: 5536d279d8edc41e2cf0a8a7c7acec1e968d1a3f

If you send that list of repos and request license redetection for them to https://github.com/contact the detected license should disappear.

For a longer term fix (ie detection of the correct license), note the problems in  https://github.com/github/choosealicense.com/issues/464 and feel free to help the various parties resolve them, if you wish to bang your head against a wall. 😬 

I'm going to close this as I don't think there's anything to be fixed in licensee currently, but feel free to continue discussing if needed.

**Comment by christianbundy** [comment]
Thanks @mlinksva, and sorry to waste your time over something so trivial. I'll check out that other issue and see if it's worth the potential concussion. Cheers!
