### ISSUE TITLE
The CPOL (Code Project Open License) is not supported

### ISSUE THREAD

**Issue by cmerat** [benbalter/licensee#193]
While it may not be the most common license, it is used by a number of projects in the .NET space. I put the request here since your gem is what powers the GitHub License API and GitHub is now the largest host of open source C# projects.

Link to the license: https://www.codeproject.com/info/cpol10.aspx

**Comment by benbalter** [comment]
@cmerat Licensee vendors the licenses from choosealicense.com. If you [follow the instructions to add a license](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license) there, Licensee will gain support for detecting the license automatically.
