### ISSUE TITLE
FYI on hash reliance

### ISSUE THREAD

**Issue by hyandell** [benbalter/licensee#194]
Just wanting to note that changes like https://github.com/benbalter/licensee/pull/171 can be painful if a user is relying on the hash coming out of licensee to be stable :)

I was supporting custom licenses by having a separate mapping of hash to license name, and spent a while scratching my head wondering why my hashes were all incorrect when I migrated to a different machine (and later version of Licensee).

Understood that y'all were fixing bugs, but just wanted to note that the hash is part of the API so that's a consideration for future bugs.

**Comment by benbalter** [comment]
@hyandell Great point, and sorry for the hassle. Yes, changes to how we normalize licenses will change the resulting hash. I was thinking of the change as a bug fix, but see now how that could be seen as a breaking change. I'll be sure to at the very least, call out any potential hash changes in the changelog.

**Comment by hyandell** [comment]
Thanks. Will close as this was just an FYI.

I should probably not rely on the hash directly - I have the file, so after learning it's not a standard hash, I can then record at the repo/file=<license> rather than hash=<license>.
