### ISSUE TITLE
Handling custom licenses

### ISSUE THREAD

**Issue by hyandell** [benbalter/licensee#196]
I've been playing with monkeypatching an additional custom license location in. This seems to be working for me:
```
Licensee::License.class_eval do

    def self.add_custom_license_dir(dir)
      @custom_license_dir=dir
    end

    def self.custom_license_dir
      return @custom_license_dir
    end

    def self.license_files
      dir=license_dir()
      files ||= Dir.glob("#{license_dir()}/*.txt")
      files.concat(Dir.glob("#{custom_license_dir()}/*.txt"))
      return files
    end

    def path
       path ||= File.expand_path "#{@key}.txt", Licensee::License.license_dir
       unless(File.exist?(path))
         path = File.expand_path "#{@key}.txt", Licensee::License.custom_license_dir
       end
       return path
    end

end
```
Would you be interested in a patch that makes that more part of the API? I would probably make custom_license_dir an array rather than a single element. Given it has to spend time doing File.exist in path, it could go further and change the path API to return nil if the files don't exist.

**Comment by hyandell** [comment]
Noting that I've added it to oss-dashboard:
  https://github.com/amzn/oss-dashboard/commit/e744c8c3015b84e8999a225ec87c0a4212de2e90
  https://github.com/amzn/oss-dashboard/commit/6b7896e7248e198515503f8c7288103f8b356450

**Comment by benbalter** [comment]
@hyandell can you explain a bit more about what you're trying to do here?

**Comment by hyandell** [comment]
Sure (sorry for the delay).

I'm using licensee on my own GitHub repositories. I want to support more licenses than the choosealicense or spdx repositories have, so I have a 2nd directory that contains my customer license files (in the same format as choosealicense/licensee).

The monkeypatching above splices that extra directory in so that licensee is looking at multiple paths for canonical licenses. Ideally I'd get that into the API as I'm sure the monkeypatching will bite me :)

**Comment by mlinksva** [comment]
I can see this being useful. It might be good to have an additional flag which directs whether licenses in the custom directory override the built-in ones. In the monkeypatch above, the custom licenses are just added to the built-in list, but the path returned is always the built-in one. I'm not sure what behavior would result in the case of a duplicate.

A use case for overriding might be some kind of self-testing in choosealicense.com, where licensee vendors its licenses from. Maybe I'll try writing a monkeypatch version over there to clarify.

**Comment by hyandell** [comment]
Agreed, overriding as an option would be useful.  For duplicates, I'd be tempted to go with cascading style so that a later license file overrides the former one. That allows for overriding a single standard one rather than all at once.

I'll update if I get a patch together.

**Comment by david-a-wheeler** [comment]
I had earlier proposed using LICENSE.spdx, in SPDX format, to allow an override.

**Comment by mlinksva** [comment]
@david-a-wheeler this issue is about adding to or overriding the set of license texts that licensee uses to match licenses, not about overriding license detection on a per-project basis if assertions can be found in the form of an SPDX file, which I understood your earlier proposal at https://github.com/benbalter/licensee/issues/85 to be about.

Am I missing something?

**Comment by david-a-wheeler** [comment]
@mlinksva : Ah, you're right.  Thanks for the clarification!
