### ISSUE TITLE
Apache 2.0 without footer not matching

### ISSUE THREAD

**Issue by hyandell** [benbalter/licensee#197]
I'm finding that this isn't matching to Apache 2.0:

https://github.com/amzn/ion-c/blob/master/LICENSE

The project owners removed the footer at the bottom.

**Comment by benbalter** [comment]
@hyandell the linked license appears to be matching for me. Is that not the case for you?

**Comment by hyandell** [comment]
It doesn't match with v8.7.0 of licensee. I just checked with v8.9.2 and that works :) Closing.
