### ISSUE TITLE
ISC license not properly detected?

### ISSUE THREAD

**Issue by j256** [benbalter/licensee#211]
Thanks for licensee.  I'm trying to get the ISC license detected by github.  I'm not sure if this is a github issue or a licensee issue.  I tried to get licensee working locally but I stopped after the 5th thing that I needed to install to do so.

As far as I can tell you have ISC in your matcher list but I've yet to find a project on github that is properly detected.  For example here's mine:

https://github.com/j256/simplejmx/blob/master/LICENSE.txt

And here's a bunch of others.

https://github.com/deepak/blog-playground
https://github.com/bbourqu/resume
https://github.com/msanterre/lymbix_ruby
https://github.com/tswaters/battlesnake_2017
https://github.com/lymbix/lymbix_ruby

How else can I help debug this?

**Comment by benbalter** [comment]
@j256 the first license linked has the text "This license is the ISC License: https://opensource.org/licenses/ISC" added. The others are missing the first paragraph. In both cases, Licensee is properly failing to match the license to ISC.

**Comment by j256** [comment]
So you are saying that it is below the threshold for matching as an ISC license because I'm identifying the license?

**Comment by j256** [comment]
Would it be possible to add some patterns to remove the license name and the URL to the license?  I've gotten a lot of requests to label my licenses over the years.  Github does that for us of course but others use my source in non-github environments.

**Comment by benbalter** [comment]
@j256 ignoring URLs could be possible. We already strip the license title if it's the beginning of the license. Additionally, the license is also missing the phrase "the above copyright notice and"

```
➜  licensee git:(master) script/git-repo https://github.com/j256/simplejmx/ --license isc
License: Other
Matched files: ["LICENSE.txt"]
LICENSE.txt:
  Content hash: f6b006d308a7b1608adb4fe194d3ea812e3b18db
  License: Other
  Closest licenses:
    * ISC similarity: 94.81%
Comparing to ISC License:
  Input length: 700
  License length: 695
  Similarity: 94.81%

diff --git a/LICENSE b/LICENSE
index b11509f..1d7af61 100644
--- a/LICENSE
+++ b/LICENSE
@@ -1,9 +1,9 @@
permission to use, copy, modify, and/or distribute this software for any purpose
with or without fee is hereby granted, provided that[-the above copyright notice-]
[-and-] this permission notice
appear in all copies. the software is provided "as is" and the author disclaims
all warranties with regard to this software including all implied warranties of
merchantability and fitness. in no event shall the author be liable for any
special, direct, indirect, or consequential damages or any damages whatsoever
resulting from loss of use, data or profits, whether in an action of contract,
negligence or other tortious action, arising out of or in connection with the
use or performance of this software. {+https://opensource.org/licenses/isc+}
```

**Comment by j256** [comment]
Wow.  Thanks.  Great feedback.  I've always felt like I didn't want a Copyright notice so I'll have to determine whether or not to add one for the sake of the license detection.

**Comment by benbalter** [comment]
> I've always felt like I didn't want a Copyright notice so I'll have to determine whether or not to add one for the sake of the license detection.

Licensee is properly failing to detect the license text as ISC, because it's been modified, and thus is not the ISC license, even if the project used ISC as a starting point.

**Comment by j256** [comment]
Yeah good points.  I've done some more reading and standardized all of my licenses to be character for character ISC.  Thanks much for the help.
