### ISSUE TITLE
Search GitHub URLs

### ISSUE THREAD

**Issue by stvnrlly** [benbalter/licensee#22]
I have a list of repos that I'm keeping stats about. It would be nice to be able to watch the license status to (1) make sure that they have a license and (2) see if it changes. I suppose that I could have a cronjob pulling them down and run on those local copies, but searching the site would be simpler.

**Comment by benbalter** [comment]
[Done](https://developer.github.com/v3/licenses/) :smile:

**Comment by stvnrlly** [comment]
Wow, even better than I had hoped. Thanks!
