### ISSUE TITLE
Add support for detecting React.js and also BSD-2-Clause-Patent

### ISSUE THREAD

**Issue by david-a-wheeler** [benbalter/licensee#220]
The Apache Foundation, and many other organizations, do not accept software licensed under the license used by React, aka BSD-2-Clause-Patent (former name BSD+Patent).  Yet this is OSI-approved.  Thus, it'd be *really* useful if licensee could specifically detect this case, because of this issue.

As far as SPDX name goes, that's what is listed here:
  https://opensource.org/licenses/BSDplusPatent
  https://opensource.org/licenses/BSD-2-Clause-Patent

More info:
https://issues.apache.org/jira/browse/LEGAL-303

**Comment by david-a-wheeler** [comment]
Correction - BSD+Patent is *different* from what React.js uses.  I'm trying to find out the SPDX license expression that would represent React.

**Comment by benbalter** [comment]
@david-a-wheeler This Gem simply vendors the licenses curated by choosealicense.com. If you follow [the instructions to add a license there](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license), this plugin should automatically get support for detecting it.

**Comment by david-a-wheeler** [comment]
Ah, thanks!  That should handle the "BSD-2-Clause-Patent" case, since that's just a specific text file.

Confusingly, the React license is *not* the same as "BSD-2-Clause-Patent", even though some people refer to the React.js license as "BSD+Patents".  I'm on the SPDX legal team mailing list talking about this; [bug 1292](https://bugs.linuxfoundation.org/show_bug.cgi?id=1292#c2) from 2015 proposed referring to the React.js license as "(BSD-3-Clause AND FB-Patents-2.0)".  This would require some tweaks to "licensee", because the text of FB-Patents-2.0 is contained in a separate PATENTS file (so licensee would have to look at *that* file to detect it).

**Comment by mlinksva** [comment]
Regarding use of BSD-3-Clause alongside a PATENTS file, I'm inclined to do nothing for now, ie close this issue. Anyone who cares about that situation can look for a PATENTS file separately.

But to throw out a potential hacky fix that I'm not endorsing: we could treat PATENTS as another potential license file. For the React situation, multiple licenses will be found so that 'other' is reported at the top level, and the existence of multiple license files would be reported.

Note that for the main react repo, that's what happens anyway (less reporting of PATENTS as one of the files), because it has LICENSE- files in addition to the main LICENSE (also the main LICENSE isn't detected because licensee has gotten stricter and it has some extra text).

```
$ script/git-repo https://github.com/facebook/react
License: Other
Matched files: ["LICENSE", "LICENSE-docs", "LICENSE-examples", "README.md"]
LICENSE:
  Content hash: 2e9614c6ac69728cffdc94333a47996a37fba275
  License: Other
  Closest licenses:
    * NCSA similarity: 63.93%
LICENSE-docs:
  Content hash: fb843d5c1df14520a512c1e31bfd7243ab55531a
  Confidence: 99.65%
  Matcher: Licensee::Matchers::Dice
  License: Creative Commons Attribution 4.0
  Closest licenses:
    * CC-BY-4.0 similarity: 99.65%
LICENSE-examples:
  Content hash: 66a44d2f0698902fa60865b3fefcc1aee2d8f650
  License: Other
README.md:
  Content hash: f0ed546ebed0ccf72013862e25b4325ff5ee93f2
  License: Other
```

**Comment by david-a-wheeler** [comment]
> Anyone who cares about that situation can look for a PATENTS file separately.

True.  But anyone who cares about these situations could also just read every LICENSE file by hand (!).  The great thing about licensee is that it detects & reports common cases in a format that is *way* easier to understand.

Looking at PATENTS as another license file isn't crazy, because it really *is* another file stating license terms.  It's not clear if the specifics you list would help.

**Comment by mlinksva** [comment]
Fair enough, it's another file stating license terms. Maybe the right thing to do _is_ to treat PATENTS as a potential license file, but not actually try to match it to any license (putting any of the licenses we know of in that file wouldn't make sense). So licensee would report its existence if it exists, and if it exists alongside another LICENSE file, licensee would report 'other' at the top level even if LICENSE matched a known license.

**Comment by david-a-wheeler** [comment]
That's an interesting idea - in particular, it's *really* easy to implement as a starting point, and that makes it clear that there's something different going on.

Instead of OTHER, if possible, it'd probably be better to report "(x and OTHER)" where "x" is what licensee normally reports (if that's possible).  So React.js would report as "(BSD-3-Clause AND OTHER)" or something like that.  When I filed this issue I thought that SDPX already had something assigned to the React clause, but that turns out not to be the case.  Until SPDX makes such an assignment, "OTHER" is a decent answer, and once SPDX makes an assignment, licensee could be enhanced to provide that kind of info.

**Comment by mlinksva** [comment]
If licensee finds multiple license files it reports 'other' at the top level, and enumerates each license file (and license detected in file, if any) found. See the example output above.

It'd be nice if it could report at the top level an SPDX expression based on the various files it found, but I'd be very wary about doing that -- unless the relationship among the files is absolutely clear, it's just going to have licensee generating false positives. FWIW there is one case in which licensee detects a single license based on multiple files -- LGPL given COPYING accompanied buy COPYING.lesser.

**Comment by david-a-wheeler** [comment]
In that case, reporting "OTHER" at the top does seem like the right way to go.

So the (meta)rule becomes: "If you see a file named PATENTS, report OTHER".  Probably ought to cover PATENTS.txt and PATENTS.md for consistency.

It's a simple rule, but it has a big plus: It means that people will *know* to look for more information.  99% of the time, if there's a BSD-3-Clause license, I just want to know that & move on (because my risk is low) - this change would mean that I could quickly detect the "something odd is happening" case, and then look at the details to try to understand it better.  A file named PATENTS *might* not impose any additional requirements, but at least I'll know to check it out.

**Comment by david-a-wheeler** [comment]
Fyi, top story today in hacker news is that Facebook will not relicense React: https://news.ycombinator.com/item?id=15050841

**Comment by benbalter** [comment]
Glad to implement a fix, just trying to get a sense of where things landed.

* Option 1: Treat PATENTS as a potential license file, meaning if LICENSE and PATENTS are both present, we'll return `other` for `Project#license`, `Project#licenses` would return `[BSD, OTHER]`, and `Project#license_files` would return both LICENSE and PATENTS, etc.

* Option 2: Special case that if a PATENTS file exists, we always return other. In this implementation, would license and licenses both return `other`, even if the license file can be determined? Would the patent file be returned as a license file?

**Comment by david-a-wheeler** [comment]
I was thinking of option two, but option one looks pretty decent too. Either approach is better than what's there now. Does anyone have a preference?

**Comment by mlinksva** [comment]
I was thinking of option one as it's transparent to the command line or library user and doesn't lead to questions asked about option 2, but either is fine with me.
