### ISSUE TITLE
Please look for filename LICENSE_1_0.txt 

### ISSUE THREAD

**Issue by hkaiser** [benbalter/licensee#221]
Projects using the Boost Software License (http://www.boost.org/LICENSE_1_0.txt) usually store their license in a file named `LICENSE_1_0.txt`. The BSL is a license which is widely used by the C++ community (https://github.com/search?utf8=%E2%9C%93&q=Boost+filename%3ALICENSE_1_0.txt&ref=simplesearch).

Would it be possible to add this file name to the list of recognized options for github to detect?

Thanks!

**Comment by benbalter** [comment]
Interesting. Do you know more about why the license has a custom filename? 

If we want to add support, it'd likely be a matter of adding another level of preference to the regex around https://github.com/benbalter/licensee/blob/master/lib/licensee/project_files/license_file.rb#L30-L31.

**Comment by hkaiser** [comment]
> Interesting. Do you know more about why the license has a custom filename?

I don't know. It just happened, I guess... The website (http://www.boost.org/users/license.html) does not mention anything explaining the choice of file name.

**Comment by mlinksva** [comment]
Seems fine to me to add another level of preference for `LICENSE_`.

Out of curiosity I'll ask Diane Cabell (see acknowledgements at the link above) if she recalls a rationale for the filename.

**Comment by hkaiser** [comment]
ping?

**Comment by hkaiser** [comment]
ping?

**Comment by hkaiser** [comment]
@benbalter Cool, thanks a lot! When will that propagate to the main site?

**Comment by hkaiser** [comment]
@benbalter it now has propagated through the trenches and the BSL is recognized properly on the community page of our project (https://github.com/STEllAR-GROUP/hpx/community). It is not recognized as the project's license on the project homepage, though: https://github.com/STEllAR-GROUP/hpx. Shouldn't it say BSL 1.0 next to 'Contributers' in the top row? 

Is there anything we have to do to make it show up there as well?
