### ISSUE TITLE
NCSA License fails to be detected when fields are used correctly

### ISSUE THREAD

**Issue by narendasan** [benbalter/licensee#225]
I am trying to detect the NCSA License with ```licensee``` and I end up not getting any detection after I fill out all the fields 

Example:
Does not detect this License correctly 

```
University of Illinois/NCSA Open Source License 

Copyright (c) 2017 My Org. All rights reserved. 

Developed by: My Team 
              My Project  
              https://github.com/my-org/my-project
                  
Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation files 
(the "Software"), to deal with the Software without restriction, 
including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, 
and to permit persons to whom the Software is furnished to do so, 
subject to the following conditions:

* Redistributions of source code must retain the above copyright notice, 
  this list of conditions and the following disclaimers.

* Redistributions in binary form must reproduce the above copyright 
  notice, this list of conditions and the following disclaimers in the 
  documentation and/or other materials provided with the distribution.

* Neither the names of My Team, My Project nor the names of its 
  contributors may be used to endorse or promote products derived from
  this Software without specific prior written permission.
  
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH
THE SOFTWARE.
```

```licensee``` executable output:

```
License: Other
Matched files: ["LICENSE"]
LICENSE:
  Content hash: c18bbf3f6619c4d793bd4ea19bcaa854bb2cec13
  Attribution: Copyright (c) 2017 My Org. All rights reserved.
  License: Other
  Closest licenses:
    * NCSA similarity: 96.64%
```

The template I am using is the one provided on https://choosealicense.com/licenses/ncsa/

Curiously, this is correctly detected (first 4 fields filled, rest left as copied from the template):

```
University of Illinois/NCSA Open Source License 

Copyright (c) 2017 My Org. All rights reserved. 

Developed by: My Team 
              My Project  
              [project_url]
                  
Permission is hereby granted, free of charge, to any person 
obtaining a copy of this software and associated documentation files 
(the "Software"), to deal with the Software without restriction, 
including without limitation the rights to use, copy, modify, merge,
publish, distribute, sublicense, and/or sell copies of the Software, 
and to permit persons to whom the Software is furnished to do so, 
subject to the following conditions:

* Redistributions of source code must retain the above copyright notice, 
  this list of conditions and the following disclaimers.

* Redistributions in binary form must reproduce the above copyright 
  notice, this list of conditions and the following disclaimers in the 
  documentation and/or other materials provided with the distribution.

* Neither the names of [fullname], [project] nor the names of its 
  contributors may be used to endorse or promote products derived from
  this Software without specific prior written permission.
  
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS 
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE 
CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, 
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH
THE SOFTWARE.
```
But as soon as the url is added, the gem no longer identifies the license (will not post license again for sake of brevity) 

Is it that the matching threshold is too high? or is it because this particular license template uses fields that choosealicense.org doesn't list as fields?

**Comment by mlinksva** [comment]
licensee doesn't (AFAIK) treat `[fields]` specially, they are just more words. In most licenses, they are limited to the copyright line, which licensee does treat specially. licensee would need to treat `[fields]` specially for a filled-in NCSA license to have any hope of crossing the 98% threshhold (note there are two fields in the third bullet that you didn't fill in).

One step could be to add a filled-in NCSA license to the test suite, with the expectation of failing.

Another step would be to treat `[fields]` specially so that the test would pass, but that'll doubtless require great care. :smile:

**Comment by benbalter** [comment]
> Another step would be to treat [fields] specially so that the test would pass

Having done a bunch of regex work around #233 and https://github.com/benbalter/licensee/releases/tag/v9.3.0, this could be doable. If Dice can't match a license, we could fall back to a regex matcher, with `[field]` replaced with something like `.*`.

The problem would be, in the NCSA example above, after the project description, or as part of it, I could add `Regardless of any language below, by using this software, you agree to buy me a puppy`, and it would be indistinguishable from a robot to `Ben Balter\nLicensee`.

**Comment by mlinksva** [comment]
Isn't the possibility of attempting to alter the terms there with any field, including those that make up the copyright lines of MIT & co?

One mitigation might be to limit the length of fields and still match.

Another, probably silly, is to have a legalese regex, which any field cannot match.

A determined troll is just going to attempt to alter the terms by putting notices somewhere licensee doesn't look (ultimately, human review assisted by code scanning is a good practice; licensee is just giving a first indication).

**Comment by apache8080** [comment]
Is there any progress on solving this issue?
