### ISSUE TITLE
CC-BY-NC-SA 4.0 misidentified

### ISSUE THREAD

**Issue by hyandell** [benbalter/licensee#228]
GitHub is identifying the following as CC-BY-SA:

  https://github.com/awsdocs/aws-go-developer-guide/blob/master/LICENSE

Licensee 9.2.1 gives me:

$ licensee aws-go-developer-guide/
License: Other
Matched files: ["LICENSE"]
LICENSE:
  Content hash: 25d0e91dacd76fecc5e7d2e2c47ede1da4fed28e
  License: Other
  Closest licenses:
    * MPL-2.0 similarity: 42.93%
    * GPL-2.0 similarity: 39.31%

This is presumably because I have removed the parts of the CC license that do not relate to the license. 

In both cases the expected result is that it should identify it as X% CC-BY-NC-SA 4.0; and I should be grumbling that SPDX have too much text in their license file.

**Comment by mlinksva** [comment]
Mostly because it was detected before better false positive avoidance for non-open CC licenses was implemented in https://github.com/benbalter/licensee/pull/168

I believe if you update the file or ask https://github.com/contact for that repo's license to be re-detected, no license will be identified.

**Comment by hyandell** [comment]
Thanks. I'm going to be changing the license, so that should take care of the GitHub 'bug'.

Should licensee do a better job at matching the license text rather than pointing to MPL or GPL?

**Comment by mlinksva** [comment]
Maybe. The reason it gives a non-intuitive list of closest matches is that it only even tries to match licenses that are close in length. With that and the CC false positive check turned off locally, I get:

```
$ script/git-repo https://github.com/awsdocs/aws-go-developer-guide
License: Other
Matched files: ["LICENSE"]
LICENSE:
  Content hash: 25d0e91dacd76fecc5e7d2e2c47ede1da4fed28e
  License: Other
  Closest licenses:
    * CC-BY-SA-4.0 similarity: 90.06%
    * CC-BY-4.0 similarity: 88.35%
    * AFL-3.0 similarity: 46.33%
    * OSL-3.0 similarity: 46.15%
    * EUPL-1.1 similarity: 45.81%
    * EPL-1.0 similarity: 42.95%
    * MPL-2.0 similarity: 42.93%
    * CC0-1.0 similarity: 42.73%
    * Apache-2.0 similarity: 42.66%
    * ECL-2.0 similarity: 42.25%
    * AGPL-3.0 similarity: 39.78%
    * GPL-3.0 similarity: 39.65%
    * GPL-2.0 similarity: 39.31%
    * Artistic-2.0 similarity: 37.40%
    * LGPL-2.1 similarity: 35.72%
    * LPPL-1.3c similarity: 35.25%
    * LGPL-3.0 similarity: 30.98%
    * OFL-1.1 similarity: 30.53%
    * MS-RL similarity: 30.22%
    * MS-PL similarity: 28.92%
    * BSD-3-Clause-Clear similarity: 26.58%
    * BSD-3-Clause similarity: 24.72%
    * BSL-1.0 similarity: 22.98%
    * BSD-2-Clause similarity: 22.73%
    * NCSA similarity: 22.44%
    * PostgreSQL similarity: 20.44%
    * MIT similarity: 20.07%
    * Unlicense similarity: 19.74%
    * ISC similarity: 17.80%
    * Zlib similarity: 17.47%
    * WTFPL similarity: 7.72%
```

I guess that's a curiosity, and more intuitive than the result without that modification. But usually note useful to do the comparisons we know aren't going to match.
