### ISSUE TITLE
Some people spell it LICENCE

### ISSUE THREAD

**Issue by rory** [benbalter/licensee#23]
Haven't looked at your code yet (and I'm not a ruby coder), but I've skimmed your docs. Some people spell it LICENCE (not LICENSE). Perhaps support that too?

**Comment by lucaswerkmeister** [comment]
e4ef84599efdbf12128141f9eb91390a57ef4ad0 ?

**Comment by benbalter** [comment]
Yep. Fixed via https://github.com/benbalter/licensee/pull/18. CC https://github.com/benbalter/licensee/issues/17
