### ISSUE TITLE
COPYRIGHT file confuses github

### ISSUE THREAD

**Issue by purpleidea** [benbalter/licensee#230]
Hi,

After running a re-license (seen here: https://github.com/purpleidea/mgmt/commit/46be83f8f79c8cb81fdf1eae9d951c70c69246b4) on my code base, GitHub no longer detects the license correctly. GH logs seem to indicate it is getting confused by the "copyright" file.

I'm assuming this is a regression, and I figured I'd ask here before I dug into the code. In particular my repo is in a very standard and common format, so I would expect this to work.

Thanks,
James

**Comment by mlinksva** [comment]
It's intentional, see #202.

**Comment by purpleidea** [comment]
@mlinksva Aha, thanks!

So the bug is that since the two files are compatible, this is breaking. I think the more correct logic should be: "of places where we've detected a license", see if there are ambiguities.

This would solve both these issues.

**Comment by mlinksva** [comment]
Yes that'd be ideal, but it'd mean we'd have to accurately detect license notices like the one in https://github.com/purpleidea/mgmt/commit/46be83f8f79c8cb81fdf1eae9d951c70c69246b4#diff-97d9303acdfc078a050e61dc5c1a9a76

It's possible but there's no code at all to do that. There is a catalog of notices to match against in SPDX's standard license header, eg https://spdx.org/licenses/GPL-3.0#licenseHeader

**Comment by akien-mga** [comment]
Just FYI, this broke license detection for Godot too: https://github.com/godotengine/godot/pull/12531
Is there a list of "safe names" that won't be parsed by licensee?

**Comment by purpleidea** [comment]
I think at this point a file in .github/legal with some sort of simple format like:
```
ignore: COPYRIGHT
ignore: foo/*.sh
```

or

```
license: GPL3+
```

in it would probably be a good approach. (I'd send a patch but GH itself is closed source!) :P

**Comment by mlinksva** [comment]
@akien-mga see https://github.com/benbalter/licensee/blob/3a2015eeedbb7d21603b132e9f3bf55a4f0237a8/lib/licensee/project_files/license_file.rb#L6-L43 for definition of filenames that licensee looks at.
