### ISSUE TITLE
Apache License 2.0 isn't detected when applied according to their instructions

### ISSUE THREAD

**Issue by AbigailBuccaneer** [benbalter/licensee#234]
The [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0) contains an appendix, that contains a boilerplate notice that contains the following line: 

```
Licensed under the Apache License, Version 2.0 (the "License"); ...
```

The GitHub repository [wiremod/wire](https://github.com/wiremod/wire) contains the text of the Apache license in the file `license`, and the boilerplate notice verbatim in `readme.md`. This results in the following:

```
$ licensee
License: Other
Matched files: ["license", "readme.md"]
license:
  Content hash: d7bc6f56cd49606d0134945d4b91ae47d3cee458
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: Apache License 2.0
readme.md:
  Content hash: a953ac3d253aaf14bf9a2d62f780811dd8b4f26e
  Attribution: Copyright 2009-2017 Wire Team
  License: Other
```

The issue here is that `readme.md` doesn't mention the phrase "Apache License 2.0", only "Apache License, Version 2.0" (which is the proper name as specified by the Apache License itself). When "Apache License, Version 2.0" is changed to "Apache License 2.0" the correct result is returned:

```
$ sed -i 's/Apache License, Version 2.0/Apache License 2.0/' readme.md
$ git add readme.md && git commit -m 'temp' --quiet
$ licensee
License: Apache License 2.0
Matched files: ["license", "readme.md"]
license:
  Content hash: d7bc6f56cd49606d0134945d4b91ae47d3cee458
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: Apache License 2.0
readme.md:
  Content hash: f4f083f8593f4451b48836075245d53ee12e2976
  Attribution: Copyright 2009-2017 Wire Team
  Confidence: 90.00%
  Matcher: Licensee::Matchers::Reference
  License: Apache License 2.0
```

I think it makes sense to consider this a bug in Licensee (or choosealicense.com's vendor files), as applying the license using Apache's own boilerplate causes the license to be incorrectly detected.

```
$ gem list licensee

*** LOCAL GEMS ***

licensee (9.5.0)
```

**Comment by mlinksva** [comment]
We follow SPDX's [lead](https://spdx.org/licenses/Apache-2.0.html) on licenses names and don't currently have a mechanism to match [standard licenses notices](https://github.com/benbalter/licensee/issues/230#issuecomment-338964588), which is what is in the README.

I think it's worth addressing this case though by making title matching a bit more flexible for Apache 2.0 as we do for a few other licenses in https://github.com/benbalter/licensee/blob/ae7de08eccf7ce97cfa0fe4ab072902d1755eaa8/lib/licensee/license.rb#L88-L140

**Comment by mlinksva** [comment]
Potential fix in #235.

Two tangential notes:

- Slightly bemused every time I see the Apache 2.0 boilerplate notice used verbatim outside of a single licensed file (see "this file" in the notice).
- Haven't looked into why, but slightly surprised Wire's license file gets a 100% match for Apache-2.0, since it has [further text appended](https://github.com/wiremod/wire/blob/80bcb4061d0aa9e8648dd70043186110cd9e329e/license#L207-L210).

**Comment by AbigailBuccaneer** [comment]
Thanks for the fix @mlinksva, that works nicely. (And you're right that Wiremod's licensing situation is a mess.)

**Comment by benbalter** [comment]
> slightly surprised Wire's license file gets a 100% match for Apache-2.0, since it has further text appended.

@mlinksva we stop once we find `END OF TERMS AND CONDITIONS`. I'd argue that any license terms or conditions after that line wouldn't be enforceable (if there were additional terms or conditions).
