### ISSUE TITLE
Disappointing false negatives and dangerous false positives

### ISSUE THREAD

**Issue by iboB** [benbalter/licensee#236]
Without knowing that this is the gem used by GitHub themselves I posted a reddit thread [here](https://www.reddit.com/r/github/comments/7c84sx/a_social_hacking_vulnerability_with_license_info/).

In short
* It's disappoiting that projects with short licenses (eg MIT) and many authors (or even a single author with a long name) aren't matched by the algorithm just because their names overshoot the 5%
* It's dangerous to assume that those 5% represent insignificant changes to the license. It is conceivable that 5% (especially for a longer license) can be used maliciously to add or change clauses

**Comment by benbalter** [comment]
@iboB thanks for opening the issue.

> It's disappoiting that projects with short licenses (eg MIT) and many authors (or even a single author with a long name) aren't matched by the algorithm just because their names overshoot the 5%

Can you provide a pull request with a failing test where this is the case? That is not the intended functionality. The license is normalized to strip the title, and version, if present, and then further strips any copyright notices (including multiple copyright notices) before comparing the license body itself. See https://github.com/benbalter/licensee/blob/b12b0d1ae11022072ae32887268bc8144aa7d105/lib/licensee/content_helper.rb#L75-L77.

> It's dangerous to assume that those 5% represent insignificant changes to the license. It is conceivable that 5% (especially for a longer license) can be used maliciously to add or change clauses

I'd love to be able to require an exact match in all cases, but humans are humans, and non-legally-significant changes sometimes sneak in. If you have any suggestions for how we could improve the algorithm, ideas and pull requests are always welcome. At the very least, any upstream provider can adjust the required confidence to 98%, 99%, 100%, etc.

**Comment by iboB** [comment]
Ah I figured it out then. My failing test wasn't because of long names, but because of different lines: The project title on a separate line above the license text. Still it would be reasonable to expect that projects with many authors can split those into multiple lines.

I'll think about possible solutions to this. Project titles and multiple lines of authors and copyright holders are quite common.

If the percent match is configurable, then I'll take this to GitHub's support. It wouldn't be unreasonable that they require 100% exact matches (ignoring whitespace, authors, and copyright holders) for the info box to appear.
