### ISSUE TITLE
Quoted Markdown licenses

### ISSUE THREAD

**Issue by christopher-dG** [benbalter/licensee#239]
Many projects in the Julia ecosystem quote the license text ([example](https://github.com/StefanKarpinski/Pkg3.jl/blob/f2100280dd5b3e6b24197afcd765293194909d07/LICENSE.md)) which tends to not be picked up by `licensee`. I think it would be doable to check:

a) Is the license a Markdown file?
b)  Do more than ~90% of the lines begin with "> "?

And if so, unquote the license text and proceed as normal. 

Thoughts? I'd be happy to give this a try myself if there's interest.

**Comment by benbalter** [comment]
@christopher-dG we could easily strip any quoted line by removing any `> ` that begins a line.

The problem, I suspect is the `The Pkg3.jl package is licensed under the MIT "Expat" License:` introduction. Is that common? If so, we have no way for a computer to know if that says "this license is MIT" or if it says "(C) 2017 All Rights Reserved. Here's a copy of the MIT license just for fun, but it's not legally binding, I just like the license text:".

**Comment by christopher-dG** [comment]
That's a valid point, I hadn't thought of that. 

The convention comes from [PkgDev.jl](https://github.com/JuliaLang/PkgDev.jl/blob/62b1beb4fb246fdcba8a000f270f555297551600/src/generate.jl#L154) which is commonly used to create new packages. The obvious alternative is to raise the issue over there and change things that way. 

As a side note, I maintain [a different package-generating package](https://github.com/invenia/PkgTemplates.jl) which does not do the quoting so that `licensee` can work properly, and [it might end up becoming the standard package generation tool](https://github.com/StefanKarpinski/Pkg3.jl/issues/23).

**Comment by mlinksva** [comment]
Closing this rather than letting stalebot do so passively eventually. :smile:

I just don't think there's a compelling reason to throw out text prefixed with `>` which could say anything, as @benbalter notes above.
