### ISSUE TITLE
'license.header' file detected in contrast to documentation

### ISSUE THREAD

**Issue by pettermahlen** [benbalter/licensee#248]
Given `LICENSE` and `license.header` (for use with https://github.com/mycila/license-maven-plugin) in the root directory, I get the following output from licensee:

```
License: Other
Matched files: ["LICENSE", "license.header"]
LICENSE:
  Content hash: d7bc6f56cd49606d0134945d4b91ae47d3cee458
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: Apache License 2.0
license.header:
  Content hash: 6a65d7401913f8c9df6b72ddf98ff0b1ca32e80b
  License: Other
```

According to the documentation, it shouldn't look at license.header. Is this a bug? What is a good way to work around it? 

An additional question is if it wouldn't be best to select the most precise match: in this case, there is a perfect match with Apache 2.0, so why not pick that rather than something that looks like noise?

**Comment by pettermahlen** [comment]
(BTW, the documentation I was referring to is https://github.com/benbalter/licensee/blob/master/docs/what-we-look-at.md).

**Comment by pettermahlen** [comment]
I renamed `license.header` to `apache2.header` and that seems to have solved it, at least when running licensee locally. It still doesn't work on github.com but I expect that's because some cache needs to expire before it tries again.

**Comment by benbalter** [comment]
@pettermahlen Can you explain a bit more about what the `license.header` file does and how widely it's used? We don't look at license headers, meaning comments on the first few lines of a code file, but we do look for all `license.*` files in the root.

**Comment by pettermahlen** [comment]
The mycila Maven license plugin can be configured with a header to use, and will then ensure that all code files in a repo have the correct license header. I had chosen to put the header in a file named license.header, and had no idea of the reason why the github.com API failed to detect a license despite everything looking correct. After a lot of searching, I ended up here, checked the documentation and concluded that everything was correctly set up (the only file type that should be checked according to the documentation was `LICENSE`, and that had identical contents to another one). Github's API provided no information about what went wrong, so eventually I installed licensee locally and noticed that it was detecting two license files.

I don't think `license.header` is likely to be a commonly used file name. But it would have saved me some time if the documentation stated that licensee in fact looks for licenses in all `license.*` files, and that if it finds two files matching the name pattern, it'll always report 'Other', which Github translates to 'no license found'. Or, perhaps, to change behaviour so that licensee only considers at files that seem to have licenses in them and does the fallback to 'Other' only if there are more than one of those?

**Comment by mlinksva** [comment]
https://github.com/search?q=filename%3Alicense.header gets 17k results. Maybe just exclude `license.header` by modifying

https://github.com/benbalter/licensee/blob/e32df8c0330f886ed0a96551f39b6db6a14e93f3/lib/licensee/project_files/license_file.rb#L10-L11
