### ISSUE TITLE
LICENSE not detected when in .github folder

### ISSUE THREAD

**Issue by lhein** [benbalter/licensee#250]
I am wondering why you don't check the .github folder of a project for the LICENSE file. This folder is used for storing specific files like README, BUILDING, CONTRIBUTING, etc. 
Shouldn't be the LICENSE file be detected in there too?

**Comment by benbalter** [comment]
@lhein Right now, Licensee only detects license files in the project's root. GitHub looks for other community files, like CONTRIBUTING, README, and SUPPORT in the `docs` folder or `.github` folder, but we specifically exclude LICENSE files from that implementation.

The idea being that while things like README or CONTRIBUTING are use/workflow documentation that users look for when needed, the LICENSE file has a notice component to it and putting it in a subfolder decreases that function. Not to mention, some projects use the design pattern of LICENSE files applying to folder trees, meaning it'd be ambiguous if the LICENSE governed the `.github` folder or the project as a whole. Last, while things like `ISSUE_TEMPLATE` may be specific to `.github`, the LICENSE is not (and thus I don't think belongs in a GitHub-specific metadata folder).

Can you explain a bit more about why you're looking to put a LICENSE file in the `.github` folder?

/cc @mlinksva

**Comment by lhein** [comment]
@benbalter I was just curious about the reasons behind your decision. Your explanation makes totally sense to me and therefore I close this issue.
