### ISSUE TITLE
When passing a file instead of directory, no file name checks should apply

### ISSUE THREAD

**Issue by sschuberth** [benbalter/licensee#266]
Currently, it's a bit weird that it is

    $ licensee ./LICENSE.apache
    License: Apache License 2.0
    Matched files: ["LICENSE.apache"]
    LICENSE.apache:
      Content hash: d7bc6f56cd49606d0134945d4b91ae47d3cee458
      Confidence: 100.00%
      Matcher: Licensee::Matchers::Exact
      License: Apache License 2.0

but

    $ cp ./LICENSE.apache noname
    $ licensee noname
    Licenses: []
    Matched files: []

I *guess* that's because Licensee ignores files that do not match a specific pattern. But IMO that logic should not be applied when passing file names directly.

**Comment by benbalter** [comment]
> should not be applied when passing file names directly.

The problem is that licensee doesn't know *how* to parse the file without looking at the filename. JSON files are parsed for `"license": "whatever"`. READMEs are parsed for a license heading. We don't know which heuristic you want to use for a `.apache` file. (But open to ideas if you have any).

**Comment by sschuberth** [comment]
My point is: It *works* for a file named `LICENSE.apache` (which also has no standard extension like `.json`), so why doesn't it work for a file named `noname`? Or is the important difference here that `LICENSE.apache` *starts* with "LICENSE" (and not that it *ends* with ".apache")?

**Comment by benbalter** [comment]
> Or is the important difference here that `LICENSE.apache` _starts_ with "LICENSE" (and not that it _ends_ with ".apache")?

That's correct. See https://github.com/benbalter/licensee/blob/master/lib/licensee/project_files/license_file.rb#L25-L43.

**Comment by sschuberth** [comment]
Hmm, just thinking out loud: When passing a single file whose name does not match any regex, would it make sense to parse it with *all* matchers and only report back the match with the highest score?

**Comment by Androbin** [comment]
Why don't we use a MIME type detector?
All Linux systems generally rely on them.

**Comment by mlinksva** [comment]
It wouldn't solve the issue: `README.md` and `LICENSE.md` have the same mime types, as one example.

I can see that it would be of some small utility to try every kind of project file we know about and report back on the results. Maybe with a flag, or even a separate script, to make sure this is what the invoker wants. Heck, it could even notice when it's been given a zip/tar/other archive file and detect as it had been given a directory. :smile:
