### ISSUE TITLE
SPDX ID gone from output?

### ISSUE THREAD

**Issue by sschuberth** [benbalter/licensee#267]
According to https://github.com/benbalter/licensee/issues/72 I believe I should see an SPDX ID along with the full license name, but I get

    $ licensee ./LICENSE.apache
    License: Apache License 2.0
    Matched files: ["LICENSE.apache"]
    LICENSE.apache:
      Content hash: d7bc6f56cd49606d0134945d4b91ae47d3cee458
      Confidence: 100.00%
      Matcher: Licensee::Matchers::Exact
      License: Apache License 2.0

where as I would have expected this to look more like

    $ licensee ./LICENSE.apache
    License: Apache License 2.0
    SPDX ID: Apache-2.0
    Matched files: ["LICENSE.apache"]
    LICENSE.apache:
      Content hash: d7bc6f56cd49606d0134945d4b91ae47d3cee458
      Confidence: 100.00%
      Matcher: Licensee::Matchers::Exact
      License: Apache License 2.0
      SPDX ID: Apache-2.0

**Comment by benbalter** [comment]
@sschuberth I believe that particular issue was referring to the GitHub API. It was inadvertently removed from the CLI when we added multiple license support. Added it back in via https://github.com/benbalter/licensee/commit/1553efdd953953818272a60b3ac2185c8aa0e4c4.

```
➜  licensee git:(master) ✗ be bin/licensee
License: MIT License (MIT)
Matched files: ["LICENSE.md", "licensee.gemspec"]
LICENSE.md:
  Content hash: 46cdc03462b9af57968df67b450cc4372ac41f53
  Attribution: Copyright (c) 2014-2017 Ben Balter
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: MIT License
licensee.gemspec:
  Confidence: 90.00%
  Matcher: Licensee::Matchers::Gemspec
  License: MIT License
```

**Comment by sschuberth** [comment]
Thanks! But could we get the SPDX ID also for the separate files? And ideally, as separate fields in any case, for easier parsing?

**Comment by benbalter** [comment]
> for easier parsing

Curious. Are you parsing the output from another script? (e.g., machine parsing versus human parsing) Would a `--json` flag or similar that returns a JSON hash be easier?

**Comment by sschuberth** [comment]
Actually, we're simply already interpreting Licensee's console output as YAML (with one minor fixup in case of non-exact matches) 😉 For details see https://github.com/heremaps/oss-review-toolkit/pull/246.
