### ISSUE TITLE
Detecting license from README.md

### ISSUE THREAD

**Issue by ioquatix** [benbalter/licensee#271]
Is this supported and if not would a PR be accepted?

**Comment by benbalter** [comment]
It is! Would gladly accept a PR to make it more clear. You must pass `detect_readme: true` to the constructor.

**Comment by ioquatix** [comment]
Hmm, so github uses licensee right?

When I run it on my repo locally, I get

```
^_^ > licensee
License: MIT License
Matched files: ["README.md", "latinum.gemspec"]
README.md:
  Content hash: 46cdc03462b9af57968df67b450cc4372ac41f53
  Attribution: Copyright, 2015, by [Samuel G. D. Williams](http://www.codeotaku.com/samuel-williams).
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: MIT License
latinum.gemspec:
  Confidence: 90.00%
  Matcher: Licensee::Matchers::Gemspec
  License: MIT License
```

Yet, on this page https://github.com/ioquatix/latinum/community it says it can't detect the license.

Is this because GitHub don't use licensee correctly?

**Comment by ioquatix** [comment]
I emailed GitHub support asking for clarification.

**Comment by benbalter** [comment]
@ioquatix Licensee has support for detecting the license in a README or via a package manager. GitHub.com has a higher standard before it will display a license, and thus doesn't look at READMEs or package managers, only license text in a LICENSE file. See https://help.github.com/articles/licensing-a-repository/.

**Comment by strugee** [comment]
@benbalter that doesn't seem to match the response I got from GitHub support? See https://github.com/isaacs/github/issues/1181#issuecomment-366000250

**Comment by ioquatix** [comment]
Here is the response I got from github:

> Hello Samuel,
> 
> Thank you for contacting GitHub Support about adding a license file to your repository.
> 
> Our license detection looks for a file named LICENSE or LICENSE.md in the root of your repository. If you place the text of your license into a file with one of those names then it should be detected and displayed at the top of your repository.
> 
> https://help.github.com/articles/adding-a-license-to-a-repository/
> 
> I hope that this is helpful to you. Let me know if I can be of further help.
> 
> Thanks,
> 
> Steve
> @slgraff
> GitHub Support

To which I said:
 
> Without actually counting, I have somewhere between 100 and 200 repositories, most with the license in the README. This also isn’t unusual, lots of projects do this to minimise the amount of boiler plate files per project.
> 
> Are you proposing I should review all those projects and add LICENSE files to them, despite the license being clearly displayed in the README, and in every source file? I’d rather avoid adding extra boiler plate.
> 
> Your license detection uses the licensee gem as per your own documentation which does correctly determine the license both from the README.md and the gemspec file (in the case of Ruby). Why have you intentionally disabled that part of the licensee detection? Is it some kind of legal issue?
> 
> Your documentation does state that using a LICENSE file is best practice, but also mentions that you can put the license in a README. Why can’t you just expand your usage of the licensee gem, which as per below, works correctly.
> 
> Kind regards,
> Samuel

Finally:

> Hi Samuel,
> 
> Currently we're not detecting Licenses contained within the README file but we've passed your feedback onto the Product team.
> 
> I can't promise if or when we'll change the current behaviour but your feedback has been taken into consideration.
> 
> Thanks
> Stacey

**Comment by ale5000-git** [comment]
@benbalter: Is it possible to pass `detect_readme: true` from command-line?

**Comment by benbalter** [comment]
@ale5000-git on the beta, that is the default, which can be toggled with `--readme` or `--no-readme`.

**Comment by ale5000-git** [comment]
I'm with v9.9.0.beta.3.
Maybe I'm missing something because it doesn't make any difference.

[Here](https://github.com/micro-a5k/microg-unofficial-installer) I have put in the README.rst `License: GPL-3.0-or-later` (the correct SPDX identifier) but it is ignored completely.

**Comment by ioquatix** [comment]
Thanks for everyone's attention to this issue.
