### ISSUE TITLE
Falsely detects MIT

### ISSUE THREAD

**Issue by iamwillbar** [benbalter/licensee#274]
licensee falsely describes this license as MIT:
https://github.com/mwaterfall/MWFeedParser/blob/master/LICENSE.txt

This license contains additional clauses that make it incompatible with MIT.

**Comment by benbalter** [comment]
Licensee is an open source project used by hosted services like GitHub which often detect licenses using prior versions of Licensee and cache the result.

If you'd like to report that a license is improperly detected by a hosted service, please contact [GitHub support](https://github.com/contact).

The latest version of LICENSEE properly detects the license:

```
➜  licensee git:(master) be bin/licensee detect https://github.com/mwaterfall/MWFeedParser/
License:        Other
Matched files:  LICENSE.txt, README.md
LICENSE.txt:
  Content hash:  5899a29fcf74c457740ad4368507bdb6c3560441
  Attribution:   Copyright (c) 2010 Michael Waterfall <michaelwaterfall@gmail.com>
  License:       Other
  Closest licenses:
    MIT similarity:      91.00%
    NCSA similarity:     78.03%
    BSL-1.0 similarity:  65.45%
README.md:
  Content hash:  5899a29fcf74c457740ad4368507bdb6c3560441
  Attribution:   Copyright (c) 2010 Michael Waterfall
  License:       Other
  Closest licenses:
    MIT similarity:      91.00%
    NCSA similarity:     78.03%
    BSL-1.0 similarity:  65.45%
```

**Comment by iamwillbar** [comment]
Sorry @benbalter! You are of course correct. Thanks for the verification, I'll let GitHub know.
