### ISSUE TITLE
9.9.0.beta.2 release does not work, no sub-commands found

### ISSUE THREAD

**Issue by sschuberth** [benbalter/licensee#275]
Something seems to be wrong with the released 9.9.0.beta.2 package. If I do

    sudo gem install licensee -v 9.9.0.beta.2

then I get

    $ licensee help
    Licensee commands:
      licensee help [COMMAND]  # Describe available commands or one specific command

    Options:
      [--remote], [--no-remote]  # Assume PATH is a GitHub owner/repo path

whereas when running from source I get

    $ bundle exec bin/licensee help
    Licensee commands:
      licensee detect [PATH]        # Detect the license of the given project
      licensee diff [PATH]          # Compare the given license text to a known license
      licensee help [COMMAND]       # Describe available commands or one specific command
      licensee license-path [PATH]  # Returns the path to the given project's license file
      licensee version              # Return the Licensee version

    Options:
      [--remote], [--no-remote]  # Assume PATH is a GitHub owner/repo path

**Comment by benbalter** [comment]
@sschuberth sorry for the delay. This was a dumb mistake that took longer than I'd like to admit to recognize. I believe the fix is in https://github.com/benbalter/licensee/commit/b6396e5fd8a3ff1b8b174453e63f8c35f26515a5. I'll cut another beta.

**Comment by benbalter** [comment]
```
$ licensee version
9.9.0.beta.3
```

🎉
