### ISSUE TITLE
License not detected

### ISSUE THREAD

**Issue by acki-m** [benbalter/licensee#276]
My project: https://github.com/rttrorg/rttr
have an MIT license, however, for unknown reason GitHub does not recognize this.
What do I have to change, in order that github recognize it?

I have already included the license text in README.md, before that, I had just a link into the LICENSE.txt
file.

**Comment by benbalter** [comment]
Licensee is an open source project used by hosted services like GitHub which often detect licenses using prior versions of Licensee and cache the result.

If you'd like to report that a license is improperly detected by a hosted service, please contact [GitHub support](https://github.com/contact) directly.

You may be able to diagnose the issue yourself. See https://github.com/benbalter/licensee/blob/master/docs/CONTRIBUTING.md#reporting-an-improperly-detected-license.

**Comment by acki-m** [comment]
I already contacted the github support team. 
They gave me this:
```
License:        Other
Matched files:  LICENSE.txt, README.md
LICENSE.txt:
  Content hash:  e7321f5ede2334b289b2e880894cb6e063e7600e
  Attribution:   Copyright (c) 2014 - 2018 Axel Menzel <info@rttr.org>
  License:       Other
  Closest licenses:
    MIT similarity:      96.30%
    NCSA similarity:     81.13%
    BSL-1.0 similarity:  68.90%
README.md:
  Content hash:  74caacd8a722717ed0abb3018d392489c700d44b
  Confidence:    90.00%
  Matcher:       Licensee::Matchers::Reference
  License:       MIT License
  Closest licenses:
    MIT similarity:      83.87%
    NCSA similarity:     71.67%
    BSL-1.0 similarity:  61.60%
```
So I have two times the license text in the readme and in the License.txt.
They say the detect only at 95%.
However, I have clearly added the license text, not modified it at all, I would consider this as a bug.
I don't know what to do anyway.

Regarding "Reporting an improperly detected license"
I have no experience with ruby at all. So providing a command like: `script/bootstrap` doesn't help me. What should I do with this? The windows `cmd` doesn't accept this of course. 
An online tool, that would be cool.

**Comment by mlinksva** [comment]
FWIW the problem is that you've added extra text to the license ("this file is part of rttr run time type reflection") which licensee has no way of knowing whether is legally significant.

```
$ bundle exec bin/licensee detect https://github.com/rttrorg/rttr --remote --license=mit
License:        Other
Matched files:  LICENSE.txt, README.md
LICENSE.txt:
  Content hash:  e7321f5ede2334b289b2e880894cb6e063e7600e
  Attribution:   Copyright (c) 2014 - 2018 Axel Menzel <info@rttr.org>
  License:       Other
  Closest licenses:
    MIT similarity:      96.30%
    NCSA similarity:     81.13%
    BSL-1.0 similarity:  68.90%
README.md:
  Content hash:  74caacd8a722717ed0abb3018d392489c700d44b
  Confidence:    90.00%
  Matcher:       Licensee::Matchers::Reference
  License:       MIT License
  Closest licenses:
    MIT similarity:      83.87%
    NCSA similarity:     71.67%
    BSL-1.0 similarity:  61.60%
Comparing to MIT License:
Input Length:      1070
License length:    1019
Similarity:      96.30%
diff --git a/LICENSE b/LICENSE
index ce3f035..3b42a29 100644
--- a/LICENSE
+++ b/LICENSE
@@ -1,14 +1,14 @@
{+this file is part of rttr run time type reflection+} permission is hereby granted,
free of charge, to any person obtaining a copy of this software and associated
documentation files the "software" , to deal in the software without
restriction, including without limitation the rights to use, copy, modify,
merge, publish, distribute, sublicense, and/or sell copies of the software, and
to permit persons to whom the software is furnished to do so, subject to the
following conditions: the above copyright notice and this permission notice
shall be included in all copies or substantial portions of the software. the
software is provided "as is", without warranty of any kind, express or implied,
including but not limited to the warranties of merchantability, fitness for a
particular purpose and noninfringement. in no event shall the authors or
copyright holders be liable for any claim, damages or other liability, whether
in an action of contract, tort or otherwise, arising from, out of or in
connection with the software or the use or other dealings in the software.
```
