### ISSUE TITLE
Apache 2.0 short-form not recognised

### ISSUE THREAD

**Issue by Krinkle** [benbalter/licensee#279]
https://github.com/cssjanus/cssjanus/blob/v1.2.2/LICENSE.txt uses the long-form and is detected (according to GitHub).

But when following the instructions at <http://www.apache.org/licenses/LICENSE-2.0#apply>, like @jakearchibald did at <https://github.com/jakearchibald/idb-keyval/blob/2.4.1/LICENCE>, then it does not appear to be recognised.

Could support for this be added?

**Comment by mlinksva** [comment]
Read the appendix again, discussed previously at https://github.com/benbalter/licensee/issues/103#issuecomment-225633548
