### ISSUE TITLE
Unable to run licensee from user install (on Travis CI)

### ISSUE THREAD

**Issue by sschuberth** [benbalter/licensee#284]
First of all, sorry for this kind of support request. I realize this might very well *not* be a bug in licensee, but as only an intermediate Rubyist I'm running out of ideas what's wrong.

I'm installing licensee version 9.9.0.beta.3 for the current user like

    gem install --user-install licensee -v 9.9.0.beta.3

And them I'm trying to run licensee like

    $(ruby -rubygems -e "puts Gem.user_dir")/bin/licensee version

As you can see in [this Travis CI build](https://travis-ci.org/sschuberth/debug-travis/builds/359862206), it fails with

    /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:271:in `find_spec_for_exe': can't find gem licensee (>= 0.a) (Gem::GemNotFoundException)
        from /home/travis/.rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems.rb:299:in `activate_bin_path'
        from /home/travis/.gem/ruby/2.4.0/bin/licensee:23:in `<main>'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /home/travis/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'

It works on a local Linux machine I have access to, however.

Any idea what's going wrong on Travis CI?

**Comment by benbalter** [comment]
@sschuberth have you tried using bundler, adding it to your Gemfile, and prepending `bundle exec`?  If you look at the backtrace above, it seems to be installing Licensee to Ruby 2.4.**0**, but then trying to run it in 2.4.**1**.

**Comment by sschuberth** [comment]
Well, I sort of know it works with `bundler`, but I'd like to avoid using it as my use case is different: I'm not using licensee as a dependency in another Ruby project, but straight as command line tool. Thus I'd like to be able to install it straight via `gem` instead of creating an "artificial" `Gemfile` and be using `bundler`.

Good point about the Ruby versions, though, I'll dig into that!

**Comment by sschuberth** [comment]
@benbalter looks like the 2.4.1 vs 2.4.0 is normal. The `Gem.user_dir` seems to zero-out the patch level so Ruby versions that only differ in the patch level can use the same gems. Any more ideas?

**Comment by benbalter** [comment]
Haven't seen this before, but two other ideas from Googling:

* `sudo gem install licensee`
* `gem update --system` before the `install` command

**Comment by sschuberth** [comment]
The latter I also already tried, it has no effect as `gem` itself is already up-to-date. The former basically works, but for portability reasons I need to install licensee per user, not in the system.
