### ISSUE TITLE
Support multi-line copyright detection?

### ISSUE THREAD

**Issue by jonathansick** [benbalter/licensee#285]
Could `Licensee::Matchers::Copyright` be modified to support copyright statements that span multiple lines (a paragraph) rather than just a single line?

### Background

My organization (@lsst) recently adopted a new policy where we put the license text (GPL v3.0) in a `LICENSE` file and maintain copyrights separately in a `COPYRIGHT` file. An example of this is [https://github.com/lsst/daf\_butler](https://github.com/lsst/daf_butler).

The issue is that GitHub/licensee doesn't detect the license for that repo. This is the output of `licensee`:

	License: Other
	Matched files: ["LICENSE", "COPYRIGHT"]
	LICENSE:
	  Content hash: f9aaff304edbbe732f27b554dcb6abe49e0b4fa0
	  Attribution: Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
	  Confidence: 100.00%
	  Matcher: Licensee::Matchers::Exact
	  License: GNU General Public License v3.0
	COPYRIGHT:
	  Content hash: b55b124b3b2c9d14da5e071b1b080dfcd78e1250
	  Attribution: Copyright 2016-2017 The Board of Trustees of the Leland Stanford Junior University,
	  License: Other

I realized that the problem is our multi-line [COPYRIGHT file](https://github.com/lsst/daf_butler/blob/master/COPYRIGHT):

	Copyright 2016-2017 The Board of Trustees of the Leland Stanford Junior University,
	through SLAC National Accelerator Laboratory
	Copyright 2018 Association of Universities for Research in Astronomy
	Copyright 2015, 2018 The Trustees of Princeton University

`licensee` detects just the first copyright line, and then interprets the rest of the text as an unknown license.

If I modify the license to be just a single line (no newlines), like this:

	Copyright 2016-2017 The Board of Trustees of the Leland Stanford Junior University, through SLAC National Accelerator Laboratory. Copyright 2018 Association of Universities for Research in Astronomy. Copyright 2015, 2018 The Trustees of Princeton University

Then `licensee` understands that `COPYRIGHT` is only a copyright statement and confidently understands the overall licensing:

	License: GNU General Public License v3.0
	Matched files: ["LICENSE", "COPYRIGHT"]
	LICENSE:
	  Content hash: f9aaff304edbbe732f27b554dcb6abe49e0b4fa0
	  Attribution: Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
	  Confidence: 100.00%
	  Matcher: Licensee::Matchers::Exact
	  License: GNU General Public License v3.0
	COPYRIGHT:
	  Content hash: da39a3ee5e6b4b0d3255bfef95601890afd80709
	  Attribution: Copyright 2016-2017 The Board of Trustees of the Leland Stanford Junior University, through SLAC National Accelerator Laboratory. Copyright 2018 Association of Universities for Research in Astronomy. Copyright 2015, 2018 The Trustees of Princeton University
	  Confidence: 100.00%
	  Matcher: Licensee::Matchers::Copyright
	  License: No-license

In my org, partner institutions contribute code to the project. Their contracts allow each institution to maintain copyright on their contributions. This is why we track multiple copyrights. Our format is that each institution gets its own line in the `COPYRIGHT` file, with the `COPYRIGHT <years> <name>` format.

To support this, I think that ideally, `licensee` would identify a paragraph starting with the word COPYRIGHT and then allow the whole paragraph to be considered the copyright statement. This behavior is also good for folks that apply hard-wrapping to their copyright statements.

What do you think? I'd add a PR myself but I don't know Ruby.

**Comment by benbalter** [comment]
Interesting. I believe this is in fact a bug.

We support multi-line copyrights in license files via https://github.com/benbalter/licensee/blob/24b216861ba4ef2757245477f9b004dd56409ecb/lib/licensee/content_helper.rb#L77-L79.

But the copyright matcher only matches if there is a single copyright notice. https://github.com/benbalter/licensee/blob/24b216861ba4ef2757245477f9b004dd56409ecb/lib/licensee/matchers/copyright.rb#L13

If a copyright file contains multiple copyrights, each line starting with a copyright marker, and that's the only content in the file, we should detect it as `no-license`, which will then get ignored at the project level.

To note, in the specific case of https://github.com/lsst/daf_butler/blob/master/COPYRIGHT, part of the problem is the line that begins `through SLAC National Accelerator Laboratory`, which isn't a copyright (and treated as license text).

Glad to review a PR that implements the described/desired behavior if anyone is interested.

**Comment by jonathansick** [comment]
I did try this:

```
Copyright 2016-2017 The Board of Trustees of the Leland Stanford Junior University, through SLAC National Accelerator Laboratory
Copyright 2018 Association of Universities for Research in Astronomy
Copyright 2015, 2018 The Trustees of Princeton University
```

And got:

	License: Other
	Matched files: ["LICENSE", "COPYRIGHT"]
	LICENSE:
	  Content hash: f9aaff304edbbe732f27b554dcb6abe49e0b4fa0
	  Attribution: Copyright (C) 2007 Free Software Foundation, Inc. <https://fsf.org/>
	  Confidence: 100.00%
	  Matcher: Licensee::Matchers::Exact
	  License: GNU General Public License v3.0
	COPYRIGHT:
	  Content hash: da39a3ee5e6b4b0d3255bfef95601890afd80709
	  Attribution: Copyright 2016-2017 The Board of Trustees of the Leland Stanford Junior University, through SLAC National Accelerator Laboratory
	  License: Other

(i.e., having a multi-line copyright where every line starts with `Copyright` and doesn't have any hard-wrapping still isn't parsed correctly).

I'm happy that this is a bug that we can just fix. We've got a Rubyist on the team so I'll see if we can get him to coach me through it.

**Comment by timj** [comment]
I've fixed the particular example in lsst/daf_butler#33. I'm not entirely sure I understand why a 100% hit on LICENSE can be derailed by something confusing found in COPYRIGHT.
