### ISSUE TITLE
LICENSE-ADDITION file

### ISSUE THREAD

**Issue by ale5000-git** [benbalter/licensee#286]
Hi,
I put the GPLv3 license in LICENSE.rst, while in LICENSE-ADDITION.rst I only put specifics of clauses like "GPLv3 or later" and the "zip exception" (so it isn't a different license but only a detail of the first).
The license isn't detected.

Can you please support this use-case?
Example: https://github.com/micro-a5k/microg-unofficial-installer

**Comment by 1138-4EB** [comment]
This is the output I get:

```
/# git clone https://github.com/micro-a5k/microg-unofficial-installer
...
/# cd microg-unofficial-installer/
/microg-unofficial-installer# licensee
License: Other
Matched files: ["LICENSE.rst", "LICENSE-ADDITION.rst"]
LICENSE.rst:
  Content hash: 2ee7d237d0f84bfaff912f2aed71da75914a90f1
  Confidence: 99.85%
  Matcher: Licensee::Matchers::Dice
  License: GNU General Public License v3.0
  Closest licenses:
    * GPL-3.0 similarity: 99.85%
    * AGPL-3.0 similarity: 95.58%
LICENSE-ADDITION.rst:
  Content hash: 1fb37d2b196b958e713ea19ff0eaa79fc5265a7c
  License: Other
```

@ale5000-git when you said that "*The license isn't detected*", did you mean by licensee or by GitHub?

**Comment by ale5000-git** [comment]
It detect `GPLv3` for `LICENSE.rst` but the problem is that for the project it say `License: Other`

**Comment by ale5000-git** [comment]
Since the `LICENSE-ADDITION.rst` contain:
>         <one line to give the program's name and a brief idea of what it does.>
>         Copyright (C) <year>  <name of author>
> 
>         This program is free software: you can redistribute it and/or modify
>         it under the terms of the GNU General Public License as published by
>         the Free Software Foundation, either version 3 of the License, or
>         (at your option) any later version.
> 
>         This program is distributed in the hope that it will be useful,
>         but WITHOUT ANY WARRANTY; without even the implied warranty of
>         MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
>         GNU General Public License for more details.
> 
>         You should have received a copy of the GNU General Public License
>         along with this program.  If not, see <https://www.gnu.org/licenses/>.

It should detect that it is the same license and not a different one (and maybe also detect the v3 or later clause).

**Comment by benbalter** [comment]
> while in LICENSE-ADDITION.rst I only put specifics of clauses like "GPLv3 or later" and the "zip exception"

Computers aren't smart enough to parse human readable legal text. As such Licensee can't determine the contents of `LICENSE-ADDITION` and does not currently support specifying licenses in such a away.

**Comment by ale5000-git** [comment]
What about just a plain text search of "This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version"?

This text is present in almost all GPL licensed projects.
It just need to remove duplicate spaces and newlines before searching.

**Comment by mlinksva** [comment]
It's conceivable we could detect and do something with known license and exception statements (as opposed to license texts) in license/copyright/notices files but that's a pretty big task, starting with figuring out what the right behavior would be. I don't see working on that on the horizon so closing this rather than let stalebot passively do so. 😄
