### ISSUE TITLE
Can't choose any EUPL license for my repository

### ISSUE THREAD

**Issue by Eagle3386** [benbalter/licensee#288]
While I did recognize  GitHub and ChooseALicense.com both support EUPL-1.2 nowadays (even chose this particular one only because of the information provided by the latter), I seem unable to set any version of the EUPL as the license for my repository:

- It's not available within the `Add a license` drop-down when [setting up a new repo](https://github.com/new), neither bei entering "European", "EUPL" and the like.
- It's not available within the `Choose a license template` [button's list](https://github.com/USERNAME/REPO-NAME/community/license/new?branch=master) (nor can one search for it over there)
- Having a file named `LICENSE` or `LICENSE.md` within my repo's root folder neither solved this.

Please help me, so that I get my chosen license shown as the GitHub documentation suggests:
![GitHub documentation](https://help.github.com/assets/images/help/repository/repo-license-indicator.png)

**Comment by benbalter** [comment]
Licensee is an open source project used to detect open source licenses. For questions about specific features on GitHub.com, please [contact GitHub Support](https://github.com/contact).

**Comment by Eagle3386** [comment]
But it *is* not correctly detected?!

**Comment by benbalter** [comment]
@Eagle3386 from [the SUPPORT file](https://github.com/benbalter/licensee/blob/master/docs/SUPPORT.md):

> Licensee is an open source project used by hosted services like GitHub and GitLab which often  detect licenses using prior versions of Licensee and cache the result.
> 
> If you'd like to report that a license is improperly detected by a hosted service, please contact [GitHub support](https://github.com/contact) or [GitLab support](https://about.gitlab.com/getting-help/) directly.

**Comment by Eagle3386** [comment]
Thanks for the update, Ben. :+1:

Last question: any benefit of having an own SUPPORT file in my repos, e. g. some fancy badge or additional functionality?

**Comment by benbalter** [comment]
Right now, if present, it is displayed to users prior to opening an issue (like the CONTRIBUTING file or Code of Conduct). See https://help.github.com/articles/adding-support-resources-to-your-project/.
