### ISSUE TITLE
Licensee CLI doesn't seems to behave correctly with detect parameter

### ISSUE THREAD

**Issue by scls19fr** [benbalter/licensee#303]
Hello,

[Licensee CLI](https://github.com/benbalter/licensee/blob/master/docs/command-line-usage.md) doesn't seems to behave correctly with `detect` parameter

Steps to reproduce
```
$ wget http://downloads.arduino.cc/libraries/github.com/bblanchon/ArduinoJson-5.13.1.zip
$ unzip ArduinoJson-5.13.1.zip
$ rm ArduinoJson-5.13.1.zip
$ licensee ArduinoJson-5.13.1/
License: MIT License
Matched files: ["LICENSE.md", "LICENSE.md"]
LICENSE.md:
  Content hash: b62d9065d1e1f216c7c944345de63973f52b71bd
  Attribution: Copyright © 2014-2018 Benoit BLANCHON
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: MIT License
LICENSE.md:
  Content hash: b62d9065d1e1f216c7c944345de63973f52b71bd
  Attribution: Copyright © 2014-2018 Benoit BLANCHON
  Confidence: 100.00%
  Matcher: Licensee::Matchers::Exact
  License: MIT License
$ licensee detect ArduinoJson-5.13.1/ --json
Licenses: []
Matched files: []
```

I wonder why `licensee ArduinoJson-5.13.1/` find 2 times `LICENSE.md`.

By default you should output a YAML file (without space in keys maybe use underscore).

My version of licensee cli come from Ubuntu 18.04 packages.
I can't say exactly which version

```
$ licensee version
Licenses: []
Matched files: []
```

(same with `$ licensee --version`)

Kind regards

**Comment by mlinksva** [comment]
Looks like it's licensee 8.9.2 https://packages.ubuntu.com/bionic/ruby-licensee

That's nearly a year old. I can't say for certain without doing more debugging, but given that the CLI options have only recently been documented and the CLI code was recently rewritten, I'm not surprised that all of the currently documented flags don't work in old versions.

**Comment by scls19fr** [comment]
What is the best way to update keeping licensee cli available from PATH?

**Comment by benbalter** [comment]
`gem install licensee` should install the latest version (as well as `gem update licensee`).

**Comment by scls19fr** [comment]
Even after this.

```bash
$ licensee version
Licenses: []
Matched files: []
```

**Comment by mlinksva** [comment]
@scls19fr try `which licensee`. You might be invoking the one installed system wide with the operating system package. https://guides.rubygems.org/faqs/#user-install points out one way to get user installed gem executables first in your PATH.

**Comment by bharatdwarkani** [comment]
I too face the similar issue in Windows 10. 

Ruby version used
ruby 2.4.4p296 (2018-03-28 revision 63013)

Licensee  ruby gem - installed using the command
gem install licensee

If I try in command prompt any of following commands

licensee version 
licensee diff [PATH] 
licensee help diff

It just returns

Licenses: []
Matched files: []

If I use a command as like this 
licensee diff "https://github.com/benbalter/licensee"

This returns expected the result

**Comment by benbalter** [comment]
Ahh. I believe I see the problem. The new command line interface isn't available until `v9.9.0`, which [is currently marked as Beta](https://github.com/benbalter/licensee/releases).

I thought there was an outstanding issue with that release, but it appears resolved on `master`, and I can try to get `9.9.0` (non-beta) released later this week, which should allow upgrading to the latest version to resolve the above problem.

**Comment by mlinksva** [comment]
@scls19fr @bharatdwarkani there's now a non-beta release out that should fix this problem. Feel free to reopen if it persists!

**Comment by scls19fr** [comment]
Fixed! Thanks @mlinksva
