### ISSUE TITLE
MPL 1.1 is not recognised

### ISSUE THREAD

**Issue by michaelklishin** [benbalter/licensee#304]
### Describe the bug

See https://github.com/rabbitmq/rabbitmq-server/pull/1609 for the background. MPL 1.1 is not recognised by `licensee` at the moment. While it is unlikely that new projects would choose it, there are some that have adopted it over a decade ago and cannot easily move to, say, MPL 2.0.

I'm happy to submit a PR in case this change would be accepted. Thank you.

### Steps to reproduce the behavior

1. Clone https://github.com/rabbitmq/rabbitmq-server
2. cd into the repo
3. Run licensee
4. Try to modify the README or files
5. Run licensee again
6. Dive into the test suite to find that "MPL" is assumed to mean "MPL 2.0"

### Expected behavior

MPL 1.1 is detected.

### Additional context

See https://github.com/rabbitmq/rabbitmq-server/pull/1609 for the background.

**Comment by mlinksva** [comment]
In case you want to help fix, the info:
- https://github.com/benbalter/licensee/blob/master/docs/what-we-look-at.md#known-licenses
- https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

**Comment by michaelklishin** [comment]
@mlinksva thanks, that's very helpful. Will look into a PR soon.

**Comment by michaelklishin** [comment]
Right, looks like MPL-1.1 has hundreds but not 1,000 repos and therefore adding support for it might be  a no-go. Fair enough, hopefully migrating to MPL2 won't be too difficult even for moderately sized projects.
