### ISSUE TITLE
GPL-3.0-or-later detection in LICENSE.spdx file

### ISSUE THREAD

**Issue by ale5000-git** [benbalter/licensee#309]
### Describe the bug

If in the file LICENSE.spdx there is `PackageLicenseDeclared: GPL-3.0` then it is detected correctly but if there is `PackageLicenseDeclared: GPL-3.0-or-later` then it say `NOASSERTION`.

In the specification: https://spdx.org/spdx-specification-21-web-version
under `Appendix I: SPDX License List ` there is this text: 
> The following table contains the full names and short identifiers for the SPDX License List, v2.5 which was released July 2016.  For the full and most up-to-date version of the SPDX License List as well as other related information, please see http://spdx.org/licenses/

Since the linked updated list include also `GPL-3.0-or-later` it should work.

### Steps to reproduce the behavior

Create a LICENSE.spdx file with `PackageLicenseDeclared: GPL-3.0-or-later` and tun licensee

### Expected behavior

It should detect `GPL-3.0-or-later`.

**Comment by mlinksva** [comment]
This would be nice to have, and work other places licensee looks where licensee looks for a SPDX license id (package manager files), most of which actually allow SPDX expressions (this is a subset of #244). 

I prototyped support for `+`, `-or-later`, and `-only` last December but didn't clean it up enough to make a PR...I'll look back at that and see if it is worth reviving or starting fresh.

**Comment by ale5000-git** [comment]
@benbalter
Is it possible to keep this open please?

**Comment by ale5000-git** [comment]
Using the license declared in LICENSE.spdx is 100% won't create any false positive, why not doing it?

**Comment by ale5000-git** [comment]
@mlinksva: Hi, any update about this?
