### ISSUE TITLE
License detection fo README works for README.md but not for README.rst

### ISSUE THREAD

**Issue by ale5000-git** [benbalter/licensee#310]
### Describe the bug

License detection fo README works for README.md but not for README.rst

### Steps to reproduce the behavior

See above

### Expected behavior

It would be nice to make it working also for README.rst

**Comment by mlinksva** [comment]
This would be a good first contribution for someone. Probably you'd need to modify`lib/licensee/project_files/readme_file.rb` and `spec/licensee/project_files/readme_file_spec.rb`.
