### ISSUE TITLE
Please update the licenses from github/choosealicense.com

### ISSUE THREAD

**Issue by ale5000-git** [benbalter/licensee#313]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

Please update the licenses from https://github.com/github/choosealicense.com

**Comment by mlinksva** [comment]
@ale5000-git there's a script to do this: https://github.com/benbalter/licensee/blob/master/script/vendor-licenses

If you'd like to run it and submit a PR, go for it. I believe @benbalter generally does that before cutting a new licensee release, but I see he added a `help wanted` label. 😄

**Comment by ale5000-git** [comment]
I have managed to install bower on Windows but I get: `npm WARN deprecated bower@1.8.4: We don't recommend using Bower for new projects. Please consider Yarn and Webpack or Parcel. You can read how to migrate legacy project here: https://bower.io/blog/2017/how-to-migrate-away-from-bower/`

This should be in the ToDO list :)
