### ISSUE TITLE
How to get licenses of opensource projects using only their name ?

### ISSUE THREAD

**Issue by sandipmgiri** [benbalter/licensee#319]
### Describe alternatives you've considered

I have got a bunch of open source projects, I want to get their licenses using only names. 
As per "licensee" document - We will get license info if we have source_url or LICENSE file or cloned source directory.
```
Detecting a project's license
This gem includes an executable which can be run using the licensee detect [PATH] command, where [PATH] is:

A directory, for example: licensee detect vendor/gems/activesupport
A file, for example: licensee detect LICENSE.txt
A GitHub repository, for example: licensee detect https://github.com/facebook/react
```
But here I'm trying to fetch licenses using only projects name. Is it possible using "licensee"? or Is there any other way to get it?

**Comment by mlinksva** [comment]
You'd like something like

`licensee detect react` to figure out that `react` probably means `https://github.com/facebook/react`?

Name->potential projects resolution feels like a different tool to me. I can imagine all kind of heuristics such a tool might use, but again, it really feels like a different set of problems, outside of licensee's scope.

Of course if you have such a tool you could use licensee to detect the licenses of projects the tool thinks a name identifies. Command line version, something like:

```bash
project-lookup react | xargs -n 1 licensee detect
```

😄

**Comment by ale5000-git** [comment]
@sandipmgiri You could you a simple shell script that download the latest master and execute licensee on it.
