### ISSUE TITLE
coveralls.io needs authorization

### ISSUE THREAD

**Issue by felixdivo** [benbalter/licensee#321]
> SOURCE NOT AVAILABLE
> The owner of this repo needs to re-authorize with github; their OAuth credentials are no longer valid so the file cannot be pulled from the github API.

See https://coveralls.io/builds/8043029/source?filename=lib%2Flicensee%2Fprojects%2Fgit_project.rb

**Comment by felixdivo** [comment]
@benbalter This is just a nice warning.

**Comment by benbalter** [comment]
Thanks! Done.
