### ISSUE TITLE
Unicode Data Files license not detected

### ISSUE THREAD

**Issue by rhdunn** [benbalter/licensee#326]
Running detect on https://github.com/espeak-ng/espeak-ng fails to detect COPYING.UCD as the unicode-dfs (Data Files and Software) license. It gives the following output for that file:

```
COPYING.UCD:
  Content hash:  acc7c8d4a9d6cb382af7963b3e9c2eee7efecfe4
  License:       NOASSERTION
  Closest licenses:
    MIT similarity:      65.10%
    BSL-1.0 similarity:  52.36%
    ISC similarity:      52.17%
```

License: http://unicode.org/copyright.html

Note: SPDX has https://spdx.org/licenses/Unicode-DFS-2016.html and https://spdx.org/licenses/Unicode-DFS-2016.html, but no version for other years.

**Comment by mlinksva** [comment]
I don't think there's any chance licensee will detect the Unicode licenses (or a vast majority of the ~300 SPDX cataloged licenses it currently doesn't detect) unless/until it is just using/vendoring the SPDX sources directly. Closing as I don't think there's anything actionable in the short term here.
