### ISSUE TITLE
Support multi-license (not dual-licensed) projects

### ISSUE THREAD

**Issue by rhdunn** [benbalter/licensee#327]
It is often the case that a project will have more than one license, especially when it mixes code from various sources. Case in point, https://github.com/espeak-ng/espeak-ng has the following licenses:

```
$ licensee 
License:        NOASSERTION
Matched files:  COPYING, COPYING.APACHE, COPYING.BSD2, COPYING.IEEE, COPYING.UCD
COPYING:
  Content hash:  f9aaff304edbbe732f27b554dcb6abe49e0b4fa0
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       GPL-3.0
COPYING.APACHE:
  Content hash:  e801a9b4965d582939632e9c5f747024a68275ab
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       Apache-2.0
COPYING.BSD2:
  Content hash:  81d871a7e9e8f1f2c5c1e032db191dce7a3664c8
  Confidence:    98.52%
  Matcher:       Licensee::Matchers::Dice
  License:       BSD-2-Clause
  Closest licenses:
    BSD-2-Clause similarity:        98.52%
    BSD-3-Clause similarity:        91.32%
    BSD-3-Clause-Clear similarity:  87.72%
COPYING.IEEE:
  Content hash:  7bf31ab62d2df2db7cfd87ff834668713384f400
  License:       NOASSERTION
  Closest licenses:
    Zlib similarity:       36.76%
    NCSA similarity:       32.43%
    Unlicense similarity:  31.40%
COPYING.UCD:
  Content hash:  acc7c8d4a9d6cb382af7963b3e9c2eee7efecfe4
  License:       NOASSERTION
  Closest licenses:
    MIT similarity:      65.10%
    BSL-1.0 similarity:  52.36%
    ISC similarity:      52.17%
```

1. `COPYING.BSD2` is the NetBSD BSD-2 license noted in #323 (which I have now amended to use the generic "COPYRIGHT HOLDER" instead of NetBSD).
2. `COPYING.UCD` is the Unicode Data Files and Software license (issue #326).
3. `COPYING.IEEE` is the declaration from http://www.realitypixels.com/turk/opensource/ for http://www.realitypixels.com/turk/opensource/#IEEEIO (no separate issue).

The project is GPL-3 licensed as a whole, so it would be useful for licensee to reflect that fact, as well as other combinations for other project license combinations.

It may also be useful to attach a confidence on the overall license like is done with matching the individual licenses.

**Comment by mlinksva** [comment]
This has been discussed in various issues in the past, [one comment](https://github.com/benbalter/licensee/pull/48#issuecomment-347668946). The crux is: licensee needs something to specify what terms the project/repo as a whole are under, probably a `LICENSE.spdx` file or a package manger file. I'd love to see this implemented, and might do so in the fullness of time.

**Comment by ebkalderon** [comment]
This would be a very nice feature to have. Many of my dual-licensed repositories show up on GitHub and elsewhere as `NOASSERTION` despite actually being `MIT OR Apache-2.0`.

**Comment by tgamblin** [comment]
Any chance this could be reopened now that GitHub has a new layout?  It seems like there is room in the new layout to display dual licenses effectively.
