### ISSUE TITLE
EUPL1.2

### ISSUE THREAD

**Issue by robstoll** [benbalter/licensee#334]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

My license does not get detected as EUPL 1.2:
https://github.com/robstoll/atrium/blob/master/LICENSE.txt

### Describe the solution you'd like

Improve your algorithm so that EUPL 1.2 get's detected as well. 
But maybe the problem is on my part and I should format the license file differently? If so, then please let me know how I should format it. Thanks :slightly_smiling_face:

**Comment by mlinksva** [comment]
This text at the top of your license file is nonstandard for EUPL-1.2 and is probably causing it to not be detected:

> Atrium © Copyright Robert Stoll <rstoll@tutteli.ch> 2017, 2018
> 
> Licensed under:

**Comment by robstoll** [comment]
I don't think that's the reason, e.g. https://github.com/nodemailer/mailparser/blob/master/LICENSE is detected as EUPL 1.1. even though there is a copyright at the beginning

**Comment by robstoll** [comment]
But you are right, it is detected if I remove the copyright. I'll have to look where I need to place it then
