### ISSUE TITLE
Add support for `/docs/LICENSE.md`

### ISSUE THREAD

**Issue by styfle** [benbalter/licensee#335]
### Is your feature request related to a problem? Please describe the problem you're trying to solve.

When GitHub Pages introduced the [/docs](https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/#publishing-your-github-pages-site-from-a-docs-folder-on-your-master-branch) folder, we moved `/LICENSE.md` to `/docs/LICENSE.md` so it would render on the [website](https://marked.js.org/#/LICENSE.md).

Now it appears that GitHub no longer sees the license (maybe it never did though).

### Describe the solution you'd like

If the license was not found in the root, check the `/docs` folder.

### Describe alternatives you've considered

An alternative is having two copies of this file, one in root and one in docs but I like to keep things [DRY](https://en.wikipedia.org/wiki/Don%27t_repeat_yourself).

Another alternative is to change our website to read the license directly from github instead of the publishes `/docs` folder. Possible but maybe not desirable.

### Additional context

Someone noticed this here: https://github.com/markedjs/marked/pull/1343

**Comment by benbalter** [comment]
Thanks for the issue. Please see https://github.com/benbalter/licensee/issues/250#issuecomment-353985847 for an explanation of our reasoning.

**Comment by benbalter** [comment]
As a workaround, you may be able to symlink the file so it appears in both locations.

**Comment by styfle** [comment]
> README or CONTRIBUTING are use/workflow documentation that users look for when needed

I think the same thing for the license, especially if github could detect it and show the license type even in the folder. I mean, contributing and license make a lot of sense to go together in my opinion.

> the LICENSE file has a notice component to it and putting it in a subfolder decreases that function.

I don't really understand this part of the argument 😅 

> some projects use the design pattern of LICENSE files applying to folder trees

This is a fair argument, my feature request was to only detect the `docs` folder if the root license was missing so monorepos should be unaffected.

> while things like `ISSUE_TEMPLATE` may be specific to `.github`, the LICENSE is not

This makes sense for `.github` folder but the `docs` folder is not github specific.

**Comment by myuseringithub** [comment]
I don't like restrictions. Let me put the LICENSE where ever I want in my project 🙃
