### ISSUE TITLE
BSD 3-clause license not detected

### ISSUE THREAD

**Issue by jermar** [benbalter/licensee#344]
### Describe the bug

A valid variant of the BSD 3-clause license is not detected. Licensee does not detect https://github.com/jermar/helenos/blob/master/LICENSE.md as a valid BSD 3-clause license. Note that this version of the BSD 3-clause uses the wording from https://directory.fsf.org/wiki/License:BSD-3-Clause. Another minor difference is the use of bullet points / dashes instead of numbered bullets. When experimenting with this, I found that the problem seems to be the former, i.e. the use of "the author" instead of "the name of the copyright holder nor the names of its contributors" in the list of conditions and "THE COPYRIGHT HOLDERS AND CONTRIBUTORS" in the disclaimer part. According to FSF and also SPDX, such a license is still a BSD 3-clause license.

### Steps to reproduce the behavior

1. Go to https://github.com/jermar/helenos
2. Click on 'View license'
3. See error, i.e. LICENSE.md is not detected as a BSD 3-clause license

### Expected behavior

According to the SPDX matching rules, even this is a BSD 3-clause license. And the wording corresponds to the FSF wording for the BSD 3-clause license.

**Comment by jermar** [comment]
Here is a diff:

$ cat LICENSE.md | licensee diff --license=bsd-3-clause                                                                                                  Wed 07 Nov 2018 01:06:47 PM CET
Comparing to BSD 3-Clause "New" or "Revised" License:
Input Length:      1314
License length:    1416
Similarity:      96.46%
diff --git a/LICENSE b/LICENSE
index 9d78289..664a903 100644
--- a/LICENSE
+++ b/LICENSE
@@ -4,16 +4,14 @@ of source code must retain the above copyright notice, this list of conditions
and the following disclaimer. - redistributions in binary form must reproduce
the above copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the distribution. -
[-neither-]the name of the [-copyright holder nor the names of its contributors-]{+author+} may {+not+} be used to endorse or promote products derived
from this software without specific prior written permission. this software is
provided by the [-copyright-]
[-holders and contributors-]{+author+} "as is" and any express or implied warranties, including,
but not limited to, the implied warranties of merchantability and fitness for a
particular purpose are disclaimed. in no event shall the [-copyright-]
[-holder or contributors-]{+author+} be liable for
any direct, indirect, incidental, special, exemplary, or consequential damages
including, but not limited to, procurement of substitute goods or services; loss
of use, data, or profits; or business interruption however caused and on any
theory of liability, whether in contract, strict liability, or tort including
negligence or otherwise arising in any way out of the use of this software, even
if advised of the possibility of such damage.

**Comment by benbalter** [comment]
@jermar @mlinksva curious if you know why the language diverges?

**Comment by jermar** [comment]
No idea. Even [OSI](https://opensource.org/licenses/BSD-3-Clause) and [FSF](https://directory.fsf.org/wiki/License:BSD-3-Clause) seem to have a different opinions about how it should read. The FSF site refers to XFree86 copyright documentation. I can find the other version also in some BSD sources. The important point though is that both versions should be considered a BSD-3-Clause license.

**Comment by mlinksva** [comment]
It diverges due to BSD and similar licenses history as templates. See "On the Variability of the BSD and MIT Licenses" doi:10.1007/978-3-319-17837-0_14

The variation @jermar presents here ideally would be detected as BSD-3-Clause as its variations are documented and allowed in https://github.com/spdx/license-list-XML/blob/bb743abd1f811c4fbf003540ce0173fca1153f5e/src/BSD-3-Clause.xml (see the `alt match` elements). However I don't think there's a good way for licensee to handle this right now.  Maybe eventually with https://github.com/benbalter/licensee/pull/254 or another implementation that learns from it.

**Comment by mlinksva** [comment]
Just for completeness, a hacky way to try to handle some of the variation presented here would be to add to the varietal words introduced at https://github.com/benbalter/licensee/pull/342/files#diff-afcc5ce738c9f9e8844392c20a677eddR39, perhaps

```ruby
  'author' => 'copyright holders and contributors'
```
