### ISSUE TITLE
diff arguments unclearly documented

### ISSUE THREAD

**Issue by tieguy** [benbalter/licensee#346]
### Describe the bug

I'd expect `licensee diff` to require and accept two arguments: PATH and an SPDX identifier. But that does not work, and neither does passing only one of the arguments.

### Steps to reproduce the behavior
If I type:

`licensee diff ./LICENSE.TXT bsd-3-clause`

I get

`ERROR: "licensee diff" was called with arguments ["./LICENSE.txt", "bsd-3-clause"]
Usage: "licensee diff [PATH]"`

But if I remove the license name (so `licensee diff ./LICENSE.txt`) I get a different error:

`You must provide an expected license
Valid licenses: (list of licenses)`

**Comment by benbalter** [comment]
@tieguy I believe it should be `licensee diff ./LICENSE.TXT --license bsd-3-clause`. Does that work?

**Comment by benbalter** [comment]
@tieguy did some digging. I agree what you're trying to do _should_ be the expected behavior, and as such it has been fixed on `master` via d81cc32.

If you'd prefer to use the released version, the following should work:

```
$ cat ./LICENSE.txt | licensee diff --license bsd-3-clause
```
