### ISSUE TITLE
Comment characters/whitespace significantly affect similarity score

### ISSUE THREAD

**Issue by tieguy** [benbalter/licensee#353]
### Describe the bug

In threetenbp's LICENSE.txt, comment characters appear to be breaking detection of the license.

### Steps to reproduce the behavior

1. Run `licensee diff --license bsd-3-clause` on https://github.com/ThreeTen/threetenbp/blob/master/LICENSE.txt - similarity is 93.88; output shows that `*` is stripped but (apparently) not `* ` - whitespace differences show up in the diff.

2. Remove`* ` from each line of LICENSE.txt ([example](https://gist.github.com/tieguy/67601914b951fb91fb626d65e099df49)) - similarity is 98.29; output shows expected outcome (no whitespace differences).

### Expected behavior

Either comment characters aren't stripped (and it fails completely, with an obvious/fixable error) or comment characters and the correct amount of whitespace are removed (and diff shows the same score either way).

### Additional context

#348 still occurs after you remove comments/whitespaces, so merely removing them won't fix threetenbp's problem.

**Comment by benbalter** [comment]
With https://github.com/benbalter/licensee/pull/354, the diff is now:

```
[-the copyright holder-]{+jsr-310+}
```

With a 99.15% match.
