### ISSUE TITLE
licensee GPL-3.0 specifier does not match haskell's cabal format

### ISSUE THREAD

**Issue by flbulgarelli** [benbalter/licensee#356]
### Describe the bug

I maintain a haskell project which is licensed using GPL-3.0. If I specify `GPL-3.0`  in the `.cabal` file, licensee detects it properly. However, If I run `cabal check`, it warns that the specifier is wrong:  

```
These warnings may cause trouble when distributing the package:
* 'license: GPL-3.0' is not a known version of that license. The known
versions are 2, 3. If this is not a mistake and you think it should be a known
version then please file a ticket.
```

This is because cabal expects `GPL-3` - no minor version. If I change the version from `GPL-3.0` to `GPL-3` and commit changes, `cabal check` works....

```
cabal check
No errors or warnings could be found in the package.
```

...but licensee does not: 

```
licensee 
License:        NOASSERTION
Matched files:  LICENSE, mulang.cabal
LICENSE:
  Content hash:  fb4942f66306942d6b76feff8169f4d138fae884
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       GPL-3.0
mulang.cabal:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::Cabal
  License:     NOASSERTION
```

 ### Steps to reproduce the behavior

1. Go to 'https://github.com/mumuki/mulang'
2. Edit and commit `.cabal` file to use `GPL-3`
3. Run licensee and verify that it is not recognizing the license, although that is the expected cabal format 

### Expected behavior

licensee should accept `GPL-3` and `GPL-2` specifiers in cabal files, and treat them exactly as `GPL-3.0` and `GPL-2.0`.

**Comment by flbulgarelli** [comment]
Also, the culprit looks to be this line, which should convert formats:  

https://github.com/benbalter/licensee/blob/16c2b2385911cb5a6af1dadeaba2ac3727ea3a96/lib/licensee/matchers/cabal.rb#L11

**Comment by mlinksva** [comment]
Here's a list of conversions:

https://github.com/ghc/packages-Cabal/blob/03becbdc3e326233ddf3aaed60edfa76ce642986/Cabal/Distribution/License.hs#L153-L164

and an example of licensee converting nonstandard names in another format

https://github.com/benbalter/licensee/blob/16c2b2385911cb5a6af1dadeaba2ac3727ea3a96/lib/licensee/matchers/dist_zilla.rb#L12-L19

in case anyone wishes to make a PR to add the conversions to `cabal.rb`.
