### ISSUE TITLE
License not detected, because of file with translated version in repository

### ISSUE THREAD

**Issue by gdsotirov** [benbalter/licensee#361]
I recently migrated an old project to GitHub with COPYING file in it, but the license wasn't properly detected (Other instead of GPL v2.0). I added file LICENSE directly in GitHub, but the problem remained. I thus installed Licensee on my Linux box to check what actually happens and here below is the output:

```
$ licensee
License:        NOASSERTION
Matched files:  LICENSE, COPYING, COPYING.bg
LICENSE:
  Content hash:  3becd209e8ed8039656c1debe01dd17b9a79208f
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       GPL-2.0
COPYING:
  Content hash:  3becd209e8ed8039656c1debe01dd17b9a79208f
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       GPL-2.0
COPYING.bg:
  Content hash:  3230f58b2c2db43a5dad90a75df16d26b0d73250
  License:       NOASSERTION
```

So apparently the file with the translated license (i.e. COPYING.bg) breaks the detection, because LICENSE and COPYING are exact matches. I'm not saying this is a bug, but is there a way to somehow tell Licensee (as a hosted service on GitHub) to ignore some files when detecting project's license? I wasn't able to find anything in this regards myself.

**Comment by mlinksva** [comment]
There isn't a way to tell Licensee (standalone or as used on GitHub AFAIK) to ignore certain files for a single repo. A workaround for, I guess https://github.com/gdsotirov/icalc is the repo, could be to move the translated license somewhere licensee won't look, perhaps append the text to `README.bg` or include in `terms.bg.html` or link to a copy of the translated license hosted elsewhere?

**Comment by mlinksva** [comment]
Speaking of linking to translated license text hosted elsewhere, I don't see Bulgarian translations listed at https://www.gnu.org/licenses/translations.html ... no idea if they'd be interested in adding, but might be worth checking since the work is done, a long time ago I guess.

**Comment by gdsotirov** [comment]
> There isn't a way to tell Licensee (standalone or as used on GitHub AFAIK) to ignore certain files for a single repo. 

It would be a nice to have...

> ... I guess https://github.com/gdsotirov/icalc is the repo...

You guess right :-)

> A workaround ... could be to move the translated license somewhere licensee won't look, perhaps append the text to `README.bg` or include in `terms.bg.html` or link to a copy of the translated license hosted elsewhere?

Yes, I though about this, but decided to explore other possibilities first. The right license is anyway linked, but I just do not like 'Other' in the summary :-)

**Comment by gdsotirov** [comment]
> Speaking of linking to translated license text hosted elsewhere, I don't see Bulgarian translations listed at https://www.gnu.org/licenses/translations.html ... no idea if they'd be interested in adding, but might be worth checking since the work is done, a long time ago I guess.

You guess right again. I do not even remember where I found the translation from (as I committed it 13 years ago), but apparently it's not even listed on GNU site...

**Comment by mlinksva** [comment]
I'm closing this as I don't think it is something licensee can fix directly. Your repo mentioned above could have its license positively identified as a side effect of addressing #368 which could cause the extension `.bg` to be ignored...if that would even be the right thing to do.
