### ISSUE TITLE
Mis-detection of AFL 3.0 as OSL 3.0

### ISSUE THREAD

**Issue by bkeepers** [benbalter/licensee#50]
```
./script/git-repo https://github.com/evan/memcached                     
Matched file: LICENSE
License: Open Software License 3.0
Confidence: 98.28526890101325%
Method: Licensee::LevenshteinMatcher
```

https://github.com/evan/memcached/blob/master/LICENSE

**Comment by benbalter** [comment]
Huh. Looks like the math is technically accurate. They are 98%+ similar. May need to add a sanity check that the license name appears in the file.
