### ISSUE TITLE
MIT is not properly detected if it does not contain the license name

### ISSUE THREAD

**Issue by bkeepers** [benbalter/licensee#53]
Since #51, the MIT is not properly detected if it doesn't contain the license name. Many projects that use the MIT license don't include the name in the license.

For example, the first one below is detected, but the second one is not.

```
$ script/git-repo https://github.com/jekyll/jekyll
License file: LICENSE
Attribution: Copyright (c) 2008-2015 Tom Preston-Werner
License: MIT License
Confidence: 100%
Method: Licensee::ExactMatcher

$ script/git-repo https://github.com/rtomayko/divvy
License file: COPYING
Attribution: Copyright (c) 2013 by Ryan Tomayko <http://tomayko.com/>
Unknown
```

**Comment by benbalter** [comment]
Yep. I believe it's no name + rewrapping. With just no name, git matcher detects it as 90% similar (there's a test for that scenerio). Need to hard code MIT as not having the title in the license so levenshtein works.

**Comment by benbalter** [comment]
```
$ script/git-repo https://github.com/rtomayko/divvy
License file: COPYING
Attribution: Copyright (c) 2013 by Ryan Tomayko <http://tomayko.com/>
License: MIT License
Confidence: 95.69569569569569%
Method: Licensee::LevenshteinMatcher
```
