### ISSUE TITLE
MIT license unrecognized

### ISSUE THREAD

**Issue by pchaigno** [benbalter/licensee#56]
[This MIT license](https://github.com/pchaigno/Julia.tmbundle/blob/license-file/LICENSE) is not recognized by Licensee:
```
License file: LICENSE
License: no license
Confidence: %
Method: NilClass
```
Is it because of the long copyright/contributors line?

EDIT: Same with [Stylus' license](https://github.com/billymoon/Stylus/blob/master/LICENSE).

**Comment by benbalter** [comment]
Which version are you using? There are some changes to the way copyrights are handled on `master` (or the latest 5.0.0b).

**Comment by pchaigno** [comment]
I was using `4.9.0`. My bad, both are well recognized with `master`.
