### ISSUE TITLE
Make dependency on rugged optional

### ISSUE THREAD

**Issue by sschuberth** [benbalter/licensee#66]
Now that there is support for filesystem-based projects, how about making the dependency on rugged optional, and only use it if it's already installed? The main reason for this being that rugged, as a native extension, can be a pain to install on some platforms, and after all a Git working tree can also be scanned by the filesystem scanner.

**Comment by benbalter** [comment]
@sschuberth makes perfect sense. Any interest in submitting a pull request to do just that?

**Comment by sschuberth** [comment]
@benbalter Interest yes, although I do not yet know how to technically do that, nor do I know when I would have some time. So if you have a clear idea how to implement it, please go ahead and do so. Otherwise I'll play around when I find some time.

**Comment by benwiley4000** [comment]
Ok, in my particular case I was able to successfully install licensee in my system after installing the `cmake` and `openssl-devel` dependencies (using `yum` in my case). Maybe this will help others running into issues.

**Comment by sschuberth** [comment]
Another thing that would help here is to talk the rugged people into [publishing pre-built binary gems](https://github.com/libgit2/rugged/issues/899).
