### ISSUE TITLE
Recognize non-standard licenses

### ISSUE THREAD

**Issue by pchaigno** [benbalter/licensee#67]
Uniquely identifying non-standard licenses would make it possible to whitelist them or detect future changes in the text of the licenses.

Currently, repositories such as [github/linguist](https://github.com/github/linguist), which have many licenses in submodules to validate, must use some custom scripts or rely on manual validations. 
Having licensee generate a unique identifier for each non-standard license would make it possible:
- to track any future modification(s) in the license text;
- and to whitelist a few common licenses, such as the [TextMate bundles license](https://github.com/textmate/ant.tmbundle#license).

The unique identifier could eventually be a hash value of the license text.

**Comment by benbalter** [comment]
Interesting. We could create a SHA1/MD5 hash of the normalized license body and expose it as `License#hash` or similar. Would that satisfy your use case?

//cc @bkeepers who may also have a use for this.

**Comment by pchaigno** [comment]
> Would that satisfy your use case?

Yes, it would :smiley:
