### ISSUE TITLE
Provide mixed-case SPDX license identifier in response (e.g., as a 'spdx' value)

### ISSUE THREAD

**Issue by david-a-wheeler** [benbalter/licensee#72]
It'd be great if this provided the SPDX 2.0 license name... or even better, a SPDX license expression where there are multiple licenses in a LICENSE{.md} file.

**Comment by benbalter** [comment]
For now, it does not support multiple licenses (see #57). That said, all license names are outputted as their SPDX name and ID. Without multiple license support, is there need to support expressions?

**Comment by david-a-wheeler** [comment]
I don't think it currently provides exactly the SPDX name.  The 'key' is close, but it's all lower case.  As I understand it, SDPX names are case-sensitive, and include 'MIT', 'GPL-2.0', and 'Intel'.   Upcasing works for 'mit' and 'gpl-2.0', but not for other licenses like 'Intel'.

Can the key be *exactly* the SPDX name?  If not, can you add a SPDX value as a result?

BTW, I'm planning to use the GitHub license API, knowing it's still in flux, to get this data from GitHub.

Of course it'd be WAY better if it could support multiple licenses :-).  But just outputting SPDX values for single-license repos would be a big help.

Thanks!

**Comment by benbalter** [comment]
> As I understand it, SDPX names are case-sensitiv

Going off of [the License Expression FAQ](http://wiki.spdx.org/view/LicenseExpressionFAQ#Is_the_License_Expression_Syntax_Case_Sensitive.3F):

> ## Is the License Expression Syntax Case Sensitive?
>
> No. One can use both upper or lower case.

Is there another standard/place we should be looking? (I thought I went down this path when I first spec'd things out, the reason their down cased is because they are filenames on disk, and Git).

**Comment by david-a-wheeler** [comment]
The license *expression* syntax is case-insensitive (e.g., and, or).  But I don't know that the license identifiers are case-insensitive.

**Comment by david-a-wheeler** [comment]
Downcasing for use as a key is perfectly sensible.  But the SPDX 2.0 spec seems to be very precise about the upper/lower case value of license identifiers, so I'd really like to use the "official" names.  I think you could just add that as a field that can be returned.

**Comment by david-a-wheeler** [comment]
Per <http://wiki.spdx.org/view/Legal_Team/Minutes/2014-09-18> the license IDs are case-insensitive, but "best practice would be to display with precise capitalization".  Can licensee provide a field (such as "spdx") with the mixed-case exact license ID name?

**Comment by benbalter** [comment]
This is now exposed as the `spdx-id` license metadata field.

**Comment by david-a-wheeler** [comment]
Awesome! Thanks.

**Comment by wking** [comment]
And with the just-landed #283, we've dropped the downcasing from `matched_license`.
