### ISSUE TITLE
Documentation: Using as a library

### ISSUE THREAD

**Issue by hyandell** [benbalter/licensee#73]
Documentation on the API and how to use from within Ruby would be great.

**Comment by hyandell** [comment]
Specifically to the pain I hit (which I acknowledge I could have solved by diving into the source) - it was easy to put together the invocation of Licensee::GitProject.new(dir) to get a license object, but it wasn't clear how to tell if a license was found, but unrecognized vs not found, or how to get the level of confidence.

**Comment by benbalter** [comment]
>  it was easy to put together the invocation of Licensee::GitProject.new(dir) to get a license object, but it wasn't clear how to tell if a license was found, but unrecognized vs not found

```ruby
project = Licensee::GitProject.new(dir)

project.license_file
=> nil # no license file 

project.license_file
=> #<Licensee::LicenseFile> # License found

project.license
=> nil # license couldn't be detected

project.license
=> #<Licensee::Licensee> 

# License file that can't be detected
project.license_file && !project.license

# No license file found
!project.license_file
```

> or how to get the level of confidence.

```ruby
project.license_file.confidence
```

**Comment by hyandell** [comment]
Ahh, thanks. I was expecting the info to be inside the license object.
