### ISSUE TITLE
Mangles attribution line by stripping non-ASCII characters

### ISSUE THREAD

**Issue by andersk** [benbalter/licensee#79]
For example, given a `COPYING` file with contents

```
Copyright © 2013–2016 by Peder Ås, 王二麻子, and Seán Ó Rudaí
```

`licensee` returns

```
License file: COPYING
Attribution: Copyright  20132016 by Peder s, , and Sen  Ruda
License: No License
Confidence: 100%
Method: Licensee::Matchers::Copyright
```

**Comment by benbalter** [comment]
I suspect https://github.com/benbalter/licensee/blob/master/lib/licensee/project_file.rb#L10 may be the culprit here.

**Comment by hyandell** [comment]
Presumably L9 now:

  @content.encode!(Encoding::UTF_8, options)

Which I think was due to a bug report on my side that Windows specific characters were causing exits.

**Comment by hyandell** [comment]
Trying this:

```
content=ARGV[0]
options = { invalid: :replace, undef: :replace, replace: '' }
content=content.encode(Encoding::UTF_8, options)
p content
puts "VALUE='#{content}'"
```

suggests the code linked to is good:

```
$ ruby test.rb 'Copyright © 2013–2016 by Peder Ås, 王二麻子, and Seán Ó Rudaí'
"Copyright © 2013–2016 by Peder Ås, 王二麻子, and Seán Ó Rudaí"
VALUE='Copyright © 2013–2016 by Peder Ås, 王二麻子, and Seán Ó Rudaí'
```

**Comment by andersk** [comment]
I notice that the problem only occurs when reading the license file out of a Git repository.

```console
$ licensee 
License file: COPYING
License hash: da39a3ee5e6b4b0d3255bfef95601890afd80709
Attribution: Copyright  20132016 by Peder s, , and Sen  Ruda
License: 
Confidence: 100.00%
Method: Licensee::Matchers::Copyright
$ rm -rf .git
$ licensee 
License file: COPYING
License hash: da39a3ee5e6b4b0d3255bfef95601890afd80709
Attribution: Copyright © 2013–2016 by Peder Ås, 王二麻子, and Seán Ó Rudaí
License: 
Confidence: 100.00%
Method: Licensee::Matchers::Copyright
```

**Comment by andersk** [comment]
The bug remains present when reading a license file out of a Git repository.

**Comment by mlinksva** [comment]
The problem seems to be that Rugged (in case of Git repository project) is always obtaining bytes (ASCII-8BIT, by design) which the encode method fails on if it encounters non-ASCII(?) characters, or with the options used, just leaves those characters out of the transcoded string.

There's surely a gentler way to fix it, but I tried out using an encoding detection/conversion dependency in #199
