### ISSUE TITLE
Exception when running `licensee` on the licensee project

### ISSUE THREAD

**Issue by callicles** [benbalter/licensee#81]
Hey !

I was trying out licensee on licensee. Although it works perfectly with some other projects, I get an exception when trying it out on the cloned licensee project itself.

I am under Mac Os X 10.11.3
ruby 2.2.1p85

```
$ licensee
/Users/nicolas/.rvm/gems/ruby-2.2.1/gems/licensee-6.1.0/lib/licensee/version.rb:1:in `<top (required)>': Licensee is not a class (TypeError)
	from /Users/nicolas/.rvm/gems/ruby-2.2.1/gems/licensee-6.1.0/lib/licensee.rb:1:in `require_relative'
	from /Users/nicolas/.rvm/gems/ruby-2.2.1/gems/licensee-6.1.0/lib/licensee.rb:1:in `<top (required)>'
	from /Users/nicolas/.rvm/gems/ruby-2.2.1/gems/licensee-6.1.0/bin/licensee:2:in `require_relative'
	from /Users/nicolas/.rvm/gems/ruby-2.2.1/gems/licensee-6.1.0/bin/licensee:2:in `<top (required)>'
	from /Users/nicolas/.rvm/gems/ruby-2.2.1/bin/licensee:23:in `load'
	from /Users/nicolas/.rvm/gems/ruby-2.2.1/bin/licensee:23:in `<main>'
	from /Users/nicolas/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/nicolas/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

Hope this helps.

**Comment by hyandell** [comment]
Also on a Mac (10.10.5).
ruby 2.0.0p481
Running licensee 8.0.0 (from path)

$ licensee 
License file: LICENSE.md
Attribution: Copyright (c) 2014-2015 Ben Balter
License: MIT License
Confidence: 100%
Method: Licensee::Matchers::Exact

**Comment by sschuberth** [comment]
@callicles I believe this has been fixed meanwhile. Do you mind trying the latest version and closing this issue if you cannot reproduce it anymore?

**Comment by callicles** [comment]
ok, let me try that

**Comment by callicles** [comment]
Cannot reproduce with last version
