### ISSUE TITLE
Apache 2.0 notice in README

### ISSUE THREAD

**Issue by mlinksva** [benbalter/licensee#82]
Some repos eg  https://github.com/jianghejie/XRecyclerView#license https://github.com/glomadrian/loading-balls#license https://github.com/Tibolte/AgendaCalendarView#license include the notice found at http://www.apache.org/licenses/LICENSE-2.0#apply in their README, much as the full text of short licenses such as MIT is fairly commonly included in full in READMEs, both often in lieu of a LICENSE file. As we detect (behind a flag) full LICENSE text in READMEs with #68 it _might_ be good to also detect the Apache 2.0 notice in that context.

On the plus side, the Apache 2.0 notice is used verbatim so could easily be detected. On the minus side, verbatim use of the notice really is intended for use in individual source files ("this file").

Alternatively, perhaps licensee should emit a warning that it has detected probable intention of using Apache 2.0 and suggest fix (adding LICENSE)?

**Comment by bkeepers** [comment]
> Alternatively, perhaps licensee should emit a warning that it has detected probable intention of using Apache 2.0 and suggest fix (adding LICENSE)?

Having licensee detect improper applications and give advice on how to apply a license properly is really interesting. :+1:

**Comment by hyandell** [comment]
A common error I see is putting the recommend Apache source header as a LICENSE file.

Not sure if this is licensee's scope, or would be something above licensee.

**Comment by mlinksva** [comment]
@hyandell indeed. I think it would be great if licensee would emit a warning for the case of the boilerplate found in LICENSE as well as if it is found in README.
