### ISSUE TITLE
Use LICENSE.spdx if available

### ISSUE THREAD

**Issue by david-a-wheeler** [benbalter/licensee#85]
I propose that if there's a file named "LICENSE.spdx" at the top level, this library should use the value of "PackageLicenseDeclared:" (if present) as the license of the package.

This lets people express _exactly_ what the license is using SPDX - so it can handle "or later", multiple licenses, or complex licensing situations.  Since it looks at "PackageLicenseDeclared", it _is_ from the developer, and since SPDX defines what the phrases mean exactly, I think you can assign a lot of confidence to this value.

This would give the licensee library a simple way to handle multiple licenses (per issue #57) with complex situations - just let the developer express it!

Don't get me wrong, I think that people should still include license text in the version control system.  But often that isn't enough.  Detecting the GPL version 2.0 license doesn't tell me if it's "GPL-2.0" (only) or "GPL-2.0+", and once multiple licenses are present, it's tricky to be confident that an automated tool can figure it out.  I think it's _safest_ to depend on a formal spec from the developer, and then use the other mechanisms when that fails.

I realize Ben already knows SPDX, but for readers of this issue who aren't aware of it, here is my [SPDX tutorial](https://github.com/david-a-wheeler/spdx-tutorial).

**Comment by nunobrito** [comment]
Just to share some thoughts on this request, I like very much idea of non-ambiguity in defining a license. Having one LICENSE with the full license terms and then another file LICENSE.spdx might seem confusing or redundant for developers to include. 

The .spdx file extension is intuitively associated to files containing SPDX tag/value data for the files inside a project, not just one field _(or do you mean the whole report to be included? If so then +1 from me, just the file name is still confusing then with the data inside) _

Other than these two remarks, I strongly support David's point that we very much need this kind of feature.

When struggling with this issue I've resorted files with .ABOUT extension to define the license without ambiguity the license. It is loosely based on how Google documents the license provenance of the Android project, documented at http://www.dejacode.org/about_spec_v0.8.0.html

A practical example:
https://github.com/dot-about/components/blob/master/samples/bootstrap-datepicker.js.ABOUT

So, on the triplecheck tooling these .ABOUT files get interpreted and apply declared licenses to specific files or the whole project folder as needed. However, these files require more fields and know-how to create them. I've tried to make this simpler with an UI that uses the SPDX identifiers at http://triplecheck.net/components/

So, perhaps it would be possible to consider instead of a name like "LICENSE.spdx" to adopt "project.about" or something that is clearly not confused? I mean this because the about format is already by at least two other open source license scanners (nexb, triplecheck).

**Comment by david-a-wheeler** [comment]
> Having one LICENSE with the full license terms and then another file LICENSE.spdx might seem confusing or redundant for developers to include.

I disagree, they fill different purposes:
* LICENSE (or similar file) is the full description of legal terms, intended for reading by humans.  Those shouldn't go away.
* LICENSE.spdx is a *computer-processable* description of the legal terms, in SPDX license expression format.  In particular, "PackageLicenseDeclared" describes the license texts using a simple language with defined terms (MIT, GPL-2.0, etc.), along with operations like "+", "AND", "OR", "WITH", and parentheses.  The terms have specific definitions (e.g., "MIT" refer to *specific* defined text).

The purpose of licensee is to figure out the license for a package, and looking at LICENSE.spdx is a good way to do it.  Unlike some packaging formats, the SPDX format has specific definitions for what "MIT" and "GPL-2.0" and "GPL-2.0" mean, so the ambiguity from other packaging formats doesn't apply.

The ABOUT spec is interesting, and clearly there's a need for a conventional format for this information. But I think the .spdx format can do at least most of the same job, and it has more support.  Here's an example:
https://github.com/linuxfoundation/cii-best-practices-badge/blob/master/LICENSE.spdx

**Comment by mlinksva** [comment]
https://github.com/search?utf8=%E2%9C%93&q=spdxversion+extension%3Aspdx&type=Code&ref=searchresults finds 27 files on GitHub.

https://github.com/spdx/tools/blob/940f08cf89a9bf41ff1217742768b06f8a8539f0/TestFiles/SPDXTagExample-v2.0.spdx looks interesting. It shows

1. tag-value format
2. licenses specified for individual files (are patterns allowed?)
3. full text of licenses used

Given (3), what's the benefit of a separate file? LICENSE can include full license text(s) as usual, SPDX annotations are an addition.

Keeping everything in one file at least for most cases would have the nice side effect of potentially allowing choosealicense.com and more importantly the GitHub repo license picker to provide a single file with bare minimum SPDX annotations and license text, and also for *GPL licenses clearly specify or later versions by default (there's no way to do that with the current non-annotated LICENSE provided, with unfortunate long-term effects).

I'd been thinking about putting annotations in YAML "front matter" of LICENSE.md files, but it appears that hack may be unnecessary.

Coming back to this issue, licensee could look for SPDX annotations in LICENSE (and other names it looks for, perhaps also with .spdx extensions) and if present and they match the included full text of the license(s), use to enrich the reported repo license.

**Comment by david-a-wheeler** [comment]
Using a separate .spdx file has the advantage that you know *exactly* what kind of file format you're dealing with, and that format's spec is defined and supported by a number of people.  SDPX files *can* include much more information about licenses, though whether or not you choose to *include* that information is up to you.

This particular issue tracker is for the "licensee" gem. I don't see a problem with licensee using *several* mechanisms to determine the license, e.g., it could look at LICENSE.spdx if it exists, then look for a special field in LICENSE, then it could examine the text of LICENSE.

**Comment by hyandell** [comment]
Agreed on the advantages of a LICENSE.spdx separate file. 

While a negative is that folk may only use that file and not have a LICENSE, that's already happening so much with pom.xml, setup.py, package.json et al's support for a license attribute.

**Comment by david-a-wheeler** [comment]
Agreed.  At least if you only include LICENSE.spdx it has a very specific meaning.

--- David A.Wheeler

**Comment by hyandell** [comment]
On that note, should licensee understand pom.xml's <license> block, setup.py's license attribute, R project's DESCRIPTION file etc?

**Comment by david-a-wheeler** [comment]
The .spdx extension is recommended in SPDX spec version 2.1 section 1.6.9, which now says: "1.6.9  ... A suggested naming convention is to use *.spdx (for tag-value format) and *-spdx.rdf for RDF format." https://bugs.linuxfoundation.org/show_bug.cgi?id=1329  I mention this in my [SPDX tutorial](https://github.com/david-a-wheeler/spdx-tutorial).

Some projects will never be detected correctly by any automated means.  Currently licensee even gets confused by multi-line copyright statements (#162). I look forward to that being fixed.  Don't get me wrong - automatic detection is great.  But having an override switch means that people will be more likely to use the tool, because with project cooperation it can handle complicated cases.

**Comment by david-a-wheeler** [comment]
Would you be willing to accept a patch?

**Comment by benbalter** [comment]
Yes! Take a look at the [NPM/Bower](https://github.com/benbalter/licensee/blob/master/lib/licensee/matchers/npm_bower_matcher.rb), [Gemspec](https://github.com/benbalter/licensee/blob/master/lib/licensee/matchers/gemspec_matcher.rb), [Dist](https://github.com/benbalter/licensee/blob/master/lib/licensee/matchers/dist_zilla_matcher.rb), and [CRAN](https://github.com/benbalter/licensee/blob/master/lib/licensee/matchers/cran_matcher.rb) matchers... it should be as simple as defining the file name and the regex to determine the license.
