### ISSUE TITLE
MIT License should be renamed to MIT Expat

### ISSUE THREAD

**Issue by connorshea** [benbalter/licensee#98]
Per [the GNU Project's list of Free Software Licenses](http://www.gnu.org/licenses/license-list.html) there are two licenses known as "The MIT License". The first is the MIT Expat license, and the second is the X11 License. The most common is the MIT Expat, but to prevent confusion they should be distinguished from one another.

I can understand wanting to keep it simple with The MIT License, and I'd be happy to help out in some way to get this working for both use-cases.

**Comment by mlinksva** [comment]
The licenses that licensee detects are included from @github/choosealicense.com

There may have been confusion at some point long ago, but the one called MIT here and https://opensource.org/licenses/MIT and http://spdx.org/licenses/MIT.html is so ubiquitous that I doubt anyone confuses it with the variant also known as X11 except willfully. BTW there are tons of other variants, see https://fedoraproject.org/wiki/Licensing:MIT

X11 might qualify to be added to the licenses cataloged in choosealicense.com; see https://github.com/github/choosealicense.com/blob/b67f10b769e1ab654e1fd941c6bf3b996755b903/CONTRIBUTING.md#adding-a-license

**Comment by connorshea** [comment]
@mlinksva I intend to open a PR for X11 in the next few days, would it be possible to rename a license ourselves to say "MIT Expat" without messing with the upstream gem?

**Comment by mlinksva** [comment]
> would it be possible to rename a license ourselves to say "MIT Expat" without messing with the upstream gem?

Not sure what you mean. Who does ourselves refer to? choosealicense.com defers to http://spdx.org/licenses/ for license names.

**Comment by connorshea** [comment]
@mlinksva ourselves is GitLab, since we use licensee to detect licenses. We're working with the FSF/GNU Project and one of their requests was regarding differentiation between the X11 and MIT Expat licenses.

We discussed this a bit more internally, and figure you're probably correct with regards to confusion.

Thanks for your time and work on this gem, and apologies for the delayed response to your initial comment.
